### PR TITLE
NumericUpDown text option for zero or null #2189

### PR DESCRIPTION
**Pull request by petvetbr**
## What changed?

Created TextIfZero and TextIfNull properties:

**TextIfZero**: If set to any other value than null, the property value will be shown when the NumericUpDownValue is equal to zero.

textzero

**TextIfNull**: If set to any other value than null, the property value will be shown when the NumericUpDownValue is null.

textnull
#2189

### CODE REVIEW

**Comment by xxMUROxx** [comment]
Well the idea is good :+1:

**Comment by thoemmi** [comment]
I'm not fond of this :-/

**Comment by xxMUROxx** [comment]
According to #2189 a compromise would be to show in that case only **0** instead of the complete `StringFormat` (e.g. **0.000**)
For the other case, now I agree with @thoemmi.

**Pull request closed without merging**
