### PR TITLE
(GH-3349) Fix disable content of ToggleButton & Button when using circle style

### LINKED ISSUE #3349: ToggleButton IsEnable=false is not working.
Since version 1.6  **ToggleButton** _IsEnable=false_ is not working properly anymore. Disabled style is applied only to button's border but not for the content.

1.6 
IsEnabled=true  -  IsEnable=false
1 6 x

1.5
IsEnabled=true  -  IsEnable=false

--
win10 vs2017 .net4.7

### PR DESCRIPTION
**Pull request by mgnslndh**
**Describe the changes you have made to improve this project**

- Added setter for the `Foreground` property to `MahApps.Styles.ToggleButton.Circle` when `IsEnabled=False`
- Added setter for the `Foreground` property to `MahApps.Styles.Button.Circle` when `IsEnabled=False`
- Updated demo with enabled/disabled version of `MahApps.Styles.Button.Circle` (current demo only display a custom derived style for Accent color)

**Closed Issues**

Closes #3349

### CODE REVIEW

**Comment by timunie** [comment]
Hi @mgnslndh for other controls MahApps uses an opaque overlay over the button /control.  I don't have a PC right now but I think I saw it at the 
SquareButton. What do you think? I will show you the file as soon as my Internet is back. :smile: 

Happy coding 
Tim

**Comment by mgnslndh** [comment]
@timunie thanks for the feedback! 

This was just a quick fix using the same solution as found on other button styles:

https://github.com/MahApps/MahApps.Metro/blob/e59402cc054ab793d879417c9bdba1cc93ce08a7/src/MahApps.Metro/Styles/Controls.Buttons.xaml#L63-L65 

https://github.com/MahApps/MahApps.Metro/blob/e59402cc054ab793d879417c9bdba1cc93ce08a7/src/MahApps.Metro/Styles/Controls.Buttons.xaml#L141-L143

https://github.com/MahApps/MahApps.Metro/blob/e59402cc054ab793d879417c9bdba1cc93ce08a7/src/MahApps.Metro/Styles/Controls.Buttons.xaml#L249-L251

I'm not aware of an easy way of doing an overlay of an elliptical control with transparent background. 

Using an overlay like for the default button style probably works well because it is rectangular and the whole content area is covered by the disabled state.

https://github.com/MahApps/MahApps.Metro/blob/e59402cc054ab793d879417c9bdba1cc93ce08a7/src/MahApps.Metro/Styles/Controls.Buttons.xaml#L412-L417

Not sure that is how the circle variant is supposed to look. Disabled state covering the whole circle. This is the expected result from the original issue:

Expected

Do you have any suggestions?

**Comment by punker76** [comment]
@mgnslndh your changes have been merged, thanks for your contribution 👍

I added 2 more samples to the demo which shows the workaround for disabled Buttons with custom Foreground (and respect the changes from GH-3121, GH-3101).

```xaml
            <StackPanel Margin="{StaticResource ControlMargin}"
                        HorizontalAlignment="Center"
                        Orientation="Horizontal">
                <ToggleButton Width="48"
                              Height="48"
                              Margin="4"
                              Foreground="{DynamicResource MahApps.Brushes.Accent}"
                              Style="{DynamicResource MahApps.Styles.ToggleButton.Circle}">
                    <ToggleButton.ContentTemplate>
                        <DataTemplate>
                            <iconPacks:PackIconModern Width="20"
                                                      Height="20"
                                                      Kind="City" />
                        </DataTemplate>
                    </ToggleButton.ContentTemplate>
                </ToggleButton>
                <ToggleButton Width="48"
                              Height="48"
                              Margin="4"
                              Foreground="{DynamicResource MahApps.Brushes.Accent}"
                              IsEnabled="False"
                              Style="{DynamicResource MahApps.Styles.ToggleButton.Circle}">
                    <ToggleButton.ContentTemplate>
                        <DataTemplate>
                            <iconPacks:PackIconModern Width="20"
                                                      Height="20"
                                                      Kind="City" />
                        </DataTemplate>
                    </ToggleButton.ContentTemplate>
                </ToggleButton>
            </StackPanel>
```

2019-09-19_15h52_26

```xaml
            <StackPanel Margin="{StaticResource ControlMargin}"
                        HorizontalAlignment="Center"
                        Orientation="Horizontal">
                <Button Width="48"
                        Height="48"
                        Margin="4"
                        Foreground="{DynamicResource MahApps.Brushes.Accent}"
                        Style="{StaticResource MahApps.Styles.Button.Circle}">
                    <Button.ContentTemplate>
                        <DataTemplate>
                            <iconPacks:PackIconModern Width="20"
                                                      Height="20"
                                                      Kind="City" />
                        </DataTemplate>
                    </Button.ContentTemplate>
                </Button>
                <Button Width="48"
                        Height="48"
                        Margin="4"
                        Foreground="{DynamicResource MahApps.Brushes.Accent}"
                        IsEnabled="False"
                        Style="{StaticResource MahApps.Styles.Button.Circle}">
                    <Button.ContentTemplate>
                        <DataTemplate>
                            <iconPacks:PackIconModern Width="20"
                                                      Height="20"
                                                      Kind="City" />
                        </DataTemplate>
                    </Button.ContentTemplate>
                </Button>
            </StackPanel>
```

2019-09-19_15h52_37

**Comment by mgnslndh** [comment]
Nice @punker76! Moving to 2.0.0 release one issue at a time :)

**Comment by timunie** [comment]
Hello @mgnslndh ,

just for information you can find my first idea below: 
image

```
<Ellipse x:Name="PART_Overlay"
         Stroke="{DynamicResource MahApps.Brushes.White}"
         Fill="{DynamicResource MahApps.Brushes.White}"
         Opacity="0.8"
         Visibility="Collapsed"
         StrokeThickness="{Binding RelativeSource={x:Static RelativeSource.TemplatedParent}, Path=BorderThickness, Converter={StaticResource BorderThicknessToStrokeThicknessConverter}}" />

[...]

<Trigger Property="IsEnabled" Value="False">
    <Setter TargetName="PART_Overlay" Property="Visibility" Value="Visible" />
</Trigger>
```

I have to agree that your and @punker76 's solution looks much nicer! Thank you :+1: 

Happy coding
Tim

**Pull request merged**
