### PR TITLE
Added windowTheme NULL check.

### PR DESCRIPTION
**Pull request by marcpiechura**
See issue #1850

### CODE REVIEW

**Comment by Amrykid** [comment]
Looks good. :+1: 

@flagbug @punker76 ?

**Comment by punker76** [comment]
@Amrykid we can do this, but what i see is, that this is in some cases (forgot to add a custom theme or accent) a user failure... so maybe we should handle this with our own exception...

**Comment by thoemmi** [comment]
If I understand the original issue #1850 correctly, this happens only in the Visual Studio designer. Maybe you should do the check for `null` only at design time (hint: [DesignerProperties.GetIsInDesignMode](https://msdn.microsoft.com/en-us/library/system.componentmodel.designerproperties.getisindesignmode.aspx))

**Comment by marcpiechura** [comment]
@thoemmi that's right, if I run the application everything is fine.

**Comment by punker76** [comment]
@thoemmi @marcpiechura so let's check for designer mode...

**Comment by marcpiechura** [comment]
@punker76 alright, should I update the pull request or do you want to add it yourself?

**Comment by punker76** [comment]
@marcpiechura simply update this pr

**Comment by punker76** [comment]
thx @marcpiechura i added your changes manually in 3f601ab

**Pull request closed without merging**
