### PR TITLE
Fix theme based styling for WindowCommands and WindowButtonCommands

### LINKED ISSUE #2560: SplitButton and DropDownButton WindowCommand styles
It would be nice to have styles for the SplitButton and DropDownButton when used in the WindowCommands.

windowscommands-dropdownbutton

### LINKED ISSUE #3447: How can I use a Menu in the window's titlebar ?
I want to put a `Menu` (because I need a single selection feature) into `RightWindowCommands` which has appearance like a `default button` inside `RightWindowCommands`.

I had try `DropdownButton`, `MenuItem`, `Menu with MenuItem`, but their appearance will be incompatible.

image

image

### LINKED ISSUE #3623: Dark Themes use LightMinButtonStyle, LightMaxButtonStyle and LightCloseButtonStyle for WindowButtonCommands
**Describe the bug**
Window button commands (minimize, maximize, close) are all using light button styles (`MahApps.Styles.Button.MetroWindow.Light`) instead of the dark (`MahApps.Styles.Button.MetroWindow.Dark`)

**To Reproduce**
1. Apply a Dark theme in App.xaml (e.g. <ResourceDictionary Source="pack://application:,,,/MahApps.Metro;component/Styles/Themes/Dark.Steel.xaml" />`)
2. Ensure the main window is of type `MetroWindow` and overrides no styles
3. Run and observe that the styles are incorrect for the WindowCommandButtons

**Expected behavior**
Dark themes should use dark styles for all controls (including WindowCommandButtons).

**Screenshots**
Without my workaround:
image

Inspecting PART_Min (button):
image

With my workaround:
image

Inspecting PART_Min (button):
image

**Environment(please complete the following information):**
 - MahApps.Metro version 2.0.0-alpha0490
 - OS: Win10 Home x64 1903
 - Visual Studio 2017 15.8.6
 - .NET Framework 4.8.03752 (targeting 4.6.1)

**Workaround**
I am able to work around this issue by adding the following to my App.xaml for now:
```
<Style TargetType="{x:Type Controls:WindowButtonCommands}" BasedOn="{StaticResource {x:Type Controls:WindowButtonCommands}}">
   <Setter Property="LightMinButtonStyle" Value="{StaticResource MahApps.Styles.Button.MetroWindow.Dark}" />
   <Setter Property="LightMaxButtonStyle" Value="{StaticResource MahApps.Styles.Button.MetroWindow.Dark}" />
   <Setter Property="LightCloseButtonStyle" Value="{StaticResource MahApps.Styles.Button.MetroWindow.Dark}" />
</Style>
```

### PR DESCRIPTION
**Pull request by punker76**
**Describe the changes you have made to improve this project**

- ThemeManager: Introduce ThemeType. This enumeration helps us to check for light and dark themes.
- Add new brush `MahApps.Brushes.WindowButtonCommands.HoverBackground`
- Add new style `MahApps.Styles.WindowCommands.Base`
- Derive style `MahApps.Styles.WindowCommands.Clean` from `MahApps.Styles.WindowCommands.Base`
- Add new style `MahApps.Styles.WindowButtonCommands.Base`
- Derive style `MahApps.Styles.WindowButtonCommands.Clean` from `MahApps.Styles.WindowButtonCommands.Base`
- `MahApps.Styles.MetroWindow.Clean` style doesn't set the `OverrideDefaultWindowCommandsBrush` to `MahApps.Brushes.Black` (it's not necessary anymore)
- Add new styles `MahApps.Styles.Button.CleanWindow.Light` and `MahApps.Styles.Button.CleanWindow.Dark`
- Fix disabled brush at `WindowCommands` and `WindowButtonCommands`
- Set the pressed background of the Min/Max/Restore/Close buttons to `MahApps.Brushes.AccentBase` and the foreground to `MahApps.Brushes.IdealForeground`
- Do not set the theme for WindowCommands and WindowButtonCommands by the Foreground. Instead look for the current theme of the application, window or flyout.
- Win10 styles for CleanWindow WindowButtonCommands
  - Add new style `MahApps.Styles.Button.CleanWindow.Close.Light.Win10`
  - Add new style `MahApps.Styles.Button.CleanWindow.Close.Dark.Win10`
  - Add new style `MahApps.Styles.WindowButtonCommands.Clean.Win10`
- Fix losing focus of opened `SplitButton`
  - Use PreviewMouseLeftButtonDown instead Click event to allow losing the focus also inside WindowCommands. Set the BorderThickness of the ListBox at the popup to 1 and don't show a focused visual.
- Add a new `SplitButton` style for WindowCommands
  - Add a new style `MahApps.Styles.SplitButton.Button.WindowCommands`
  - Add a new style `MahApps.Styles.SplitButton.ButtonArrow.WindowCommands`
  - Add a new style `MahApps.Styles.SplitButton.WindowCommands` which will be used for all SplitButton inside  WindowCommands
- Add a new DropDownButton style for WindowCommands
  - Add a new style `MahApps.Styles.DropDownButton.Button.WindowCommands`
  - Add a new style `MahApps.Styles.DropDownButton.WindowCommands` which will be used for all DropDownButton inside  WindowCommands
- Improve overflow WindowCommands

**Closed Issues**

Closes #3623 
Closes #2560 
Closes #3447

### CODE REVIEW

**Comment by timunie** [comment]
Good morning @punker76 ,

will this also address #2560 ?

Happy coding
Tim

**Comment by punker76** [comment]
> Good morning @punker76 ,
> 
> will this also address #2560 ?
> 
> Happy coding
> Tim

@timunie Yes, I'll add a styling for the SplitButton.

**Comment by punker76** [comment]
@timunie 

2019-10-30_23h02_02

**Comment by timunie** [comment]
Hi @punker76 

many thanks it looks really promissing. I think many people will have a benefit of this.

Meanwhile I created a `Style` for the `DropDownButton`. Do you want it? If you mark this post with :+1: 	I will make a PR.
Change_Language

Happy coding 
Tim

**Comment by punker76** [comment]
@timunie 😉 

2019-10-31_15h37_39

**Comment by punker76** [comment]
@timunie Improved overflow WindowCommands

2019-11-02_18h37_48

**Pull request merged**
