### PR TITLE
Resolved #2820

### LINKED ISSUE #2820: MahApps.Metro's borderlesswindowbehavior does not work with stickywindows.
## What steps will reproduce this issue?

StickyWindow library does not work in combination with MahApps.Metro custom border when you are dragging the form, resizing the form works like it should, Disabling BorderlessWindowBehavior makes it work but only when dragging the normal windows border, MahApps.Metro doesn't seem to raise the events Stickywindow needs when dragging.
Library can be found here: 
http://programminghacks.net/2009/10/19/download-snapping-sticky-magnetic-windows-for-wpf/

XAML:
```
<controls:MetroWindow x:Class="MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:controls="http://metro.mahapps.com/winfx/xaml/controls"
        xmlns:i="http://schemas.microsoft.com/expression/2010/interactivity"
        xmlns:Behaviours="http://metro.mahapps.com/winfx/xaml/shared"  
        xmlns:local="clr-namespace:MainProgram"
        Title="MainWindow" Height="212.148" Width="267.046" ResizeMode="NoResize" WindowStartupLocation="CenterScreen">
    <i:Interaction.Behaviors>
        <local:StickyWindowBehavior />
        <!--BorderlessWindowBehavior breaks the StickyWindowBehavior-->
        <Behaviours:BorderlessWindowBehavior />
        <Behaviours:WindowsSettingBehaviour />
        <Behaviours:GlowWindowBehavior />
    </i:Interaction.Behaviors>
    <Grid>
    </Grid>
</controls:MetroWindow>
```

StickyWindowBehavior.cs:
```
using Blue.Windows;
using System.Windows;
using System.Windows.Interactivity;

namespace MainProgram {
  public class StickyWindowBehavior : Behavior<Window> {
    private StickyWindow stickWindow;

    protected override void OnAttached() {
      base.OnAttached();
      AssociatedObject.Loaded += delegate {
        stickWindow = new StickyWindow(AssociatedObject) { StickToScreen = true, StickToOther = true, StickOnResize = true, StickOnMove = true };
      };
    }

    protected override void OnDetaching() {
      base.OnDetaching();
      if (stickWindow != null)
        stickWindow.ReleaseHandle();
    }
  }
}
```

### Expected outcome

The windows that have the StickyWindowBehavior should be sticky when the borders are close to eachother while dragging the window around.

### Environment

- MahApps.Metro __v1.4.1__
- Windows __7/8/8.1/10__
- Visual Studio __2015__
- .NET Framework __4.6.1__

### PR DESCRIPTION
**Pull request by RyadaProductions**
Reapplied bug fix from d70c3c955d49c658527a02c122612e970ece2251.

## What changed?

_Describe the changes you have made to improve this project._
Reapplied a bugfix for StickyWindow, which was added in 2013 but removed late 2015.
Normal users should not notice any change.

_Closed issues._
#2820

### CODE REVIEW

**Comment by nighthound** [comment]
Hi, I'm curious why this is on hold for more than a year. Is window snapping functionality something that will be included in 2.0 and hence not being merged?

**Comment by thoemmi** [comment]
@punker76 Is there a chance that this PR will be merged? This issue was reported to **StickyWindows** too: https://github.com/thoemmi/StickyWindows/issues/7

**Comment by RyadaProductions** [comment]
If there is anything I must do to make the merge possible please let me know. As I am wondering why its not merged yet.

**Comment by punker76** [comment]
@thoemmi I will look for it. First I must check why I changed this, because something needs this...

**Comment by punker76** [comment]
@thoemmi @RyadaProductions I found the issue and pr which introduces the change #2324 PR #2326. But, I could not reproduce this issue with the latest source. So I added your changes.

@thoemmi If I set StickOnMove to true then I can not move a maximized Window. This happens without MahApps too, so is this a normal behabior? If I set it to false then I can do this.

**Comment by thoemmi** [comment]
Thanks @punker76. I'll check that issue (I hardly do any GUI work anymore, that's why I got so quiet in the recent past)

**Comment by JobaDiniz** [comment]
Hi, is possible to release this fix into a new version of 1.X? Maybe `1.6.6`? I need this functionality into 1.6.x, moving to 2.X is a major breaking change for me, as we have developed a full IDE relying on MahApps + [Gemini](https://github.com/tgjones/gemini/) and 2.X breaks several things.

**Pull request closed without merging**
