### PR TITLE
ClearTextButtonBehavior to acheive a better handling

### LINKED ISSUE #1268: TextBox with textboxhelper cleartextbtn doesnt work after visibilty change
Hi,
I have a grid with 2 columns.
col 0 is visible and have a button that change the visibility col 1 visible.
in col 0 the textbox which works fine:

                    <TextBox Grid.Col="0" VerticalAlignment="Center"
                             Text="{Binding Model.ComputerName, Delay=2500,
                                            UpdateSourceTrigger=PropertyChanged,
                                            Mode=TwoWay}"
                             controls:TextboxHelper.ClearTextButton="True"
                             controls:TextboxHelper.Watermark="{Binding Path=Model.TotalCount,
                                                                        StringFormat='{} Any ({0})'}" />

and in col 1 i have the same text box (with different text binding property).
the problame is that in col 1 (after visibilty of the grid change to visible) the cleartextbutton doesnt work (it appears but not clearing the text).
if i remove the visibility binding from the grid so both columns will be visible it works.
any ideas for a solution?
thanks.

### PR DESCRIPTION
**Pull request by punker76**
sometimes the `TextBoxHelper` loaded methods for `TextBox`, `PasswordBox` and `ComboBox` doesn't work correct.

so this PR should fix this and should not a braking change :-D

Closes #1268

### CODE REVIEW

**Comment by punker76** [comment]
^^ @thoemmi @flagbug 
/cc @JoeRobich @fuzzylee @arnoldpa @gilimak

**Comment by punker76** [comment]
image

**Comment by arnoldpa** [comment]
Works fine for me.

On short question: is the behavior wanted that after TextBoxHelper.ButtonCommand executed Control.Clear() get executed too?

**Comment by punker76** [comment]
@arnoldpa you have different scenarios (e.g. for a `TextBox`)

1) a `MetroTextBox` with `ClearTextButton="True"`: it clears the text
```xaml
<TextBox Controls:TextBoxHelper.ClearTextButton="True" />
```
2) a `MetroTextBox` with `ClearTextButton="True"` and button command: it fires the command and clears the text
```xaml
<TextBox Controls:TextBoxHelper.ClearTextButton="True"
         Controls:TextBoxHelper.ButtonCommand="{Binding TextBoxButtonCmd, Mode=OneWay}" />
```
3) a `SearchMetroTextBox` or `MetroButtonTextBox` with `ClearTextButton="True"` and button command: it fires the command and clears the text
```xaml
<TextBox Controls:TextBoxHelper.ClearTextButton="True"
         Controls:TextBoxHelper.ButtonCommand="{Binding TextBoxButtonCmd, Mode=OneWay}" />
```
4) a `SearchMetroTextBox` or `MetroButtonTextBox` with `ClearTextButton="False"` and button command: it fires only the command
```xaml
<TextBox Controls:TextBoxHelper.ClearTextButton="False"
         Controls:TextBoxHelper.ButtonCommand="{Binding TextBoxButtonCmd, Mode=OneWay}" />
```

**Comment by arnoldpa** [comment]
thank you, now its clear for me :)

**Comment by JobaDiniz** [comment]
Hi, how can I show the button in the textbox, but replace the clear command entirely?
I want only my command to be fired, that is, textbox text should not be cleared.

**Pull request merged**
