### PR TITLE
DependencyProperty DisplayFormat for DateTimePicker and TimePicker

### PR DESCRIPTION
**Pull request by mosberger**
Customizable format of the displayed Date / DateTime.
The default value is still the format of the SpecificCultureInfo.

### CODE REVIEW

**Comment by mosberger** [comment]
Well, I think this change has already been made with #2930.

**Comment by punker76** [comment]
@xxMUROxx Can we maybe merge this together with #2930 ?

**Comment by mosberger** [comment]
@punker76 I think the solution of @xxMUROxx  is more complete than mine. You can delete my pull request. 
Sorry for not checking the open pull requests.

**Comment by xxMUROxx** [comment]
@punker76 @mosberger My solution allows only to specify whether to have short/long time/date. @mosberger s solution does allow custom formatting.

Lets discuss about whether or not we should provide a custom string format on TimePicker/DateTimePicker. My opinion is to have a behavior like MS provided it in DatePicker; to not let the user change the string Format like he wants to. Why do we need this bahavior. For each culture the date-time format is already predefined since ages.

**Pull request closed without merging**
