### PR TITLE
[WIP] Ribbon menu support

### PR DESCRIPTION
**Pull request by Tide**
@punker76 Fixed pop up issue and code cleanup.
@kiangtengl Styled the ribbon button, split button, menu button and radio button.
@Tide Made changes to the ribbon demo and merged in latest master.

### CODE REVIEW

**Comment by petersondrew** [comment]
:+1: Would love to see this released.

**Comment by punker76** [comment]
@petersondrew i dont think that we finish this, but as alternative you can use this cool lib that also understands MahApps https://fluent.codeplex.com/

**Comment by CADbloke** [comment]
putting the new GitHub link to [Fluent.Ribbon](https://github.com/fluentribbon/Fluent.Ribbon) here for travellers from the future.

**Comment by punker76** [comment]
@CADbloke :+1:

**Pull request closed without merging**
