### PR TITLE
Revert "AutomationId based on name fix"

### PR DESCRIPTION
**Pull request by punker76**
Reverts MahApps/MahApps.Metro#2381

affected by https://github.com/MahApps/MahApps.Metro/pull/2386#issuecomment-191647522

### CODE REVIEW

**Comment by vipinnair** [comment]
I downloaded a new copy today March 8, I can see the solution is broken. a lot of errors.

**Comment by punker76** [comment]
@vipinnair ...and what errors???

**Comment by vipinnair** [comment]
Majority of them silly issues occuring in classes WindowButtonCommands. Its giving syntax error but I dont have its actually a syntax error. 

Error	88	; expected	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	223	65	MahApps.Metro.NET45
Error	89	; expected	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	223	66	MahApps.Metro.NET45
Error	91	; expected	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	227	21	MahApps.Metro.NET45
Error	95	; expected	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	235	63	MahApps.Metro.NET45
Error	96	; expected	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	235	64	MahApps.Metro.NET45
Error	98	; expected	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	239	21	MahApps.Metro.NET45

**Comment by vipinnair** [comment]
Error	88	; expected	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	223	65	MahApps.Metro.NET45
Error	89	; expected	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	223	66	MahApps.Metro.NET45
Error	91	; expected	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	227	21	MahApps.Metro.NET45
Error	95	; expected	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	235	63	MahApps.Metro.NET45
Error	96	; expected	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	235	64	MahApps.Metro.NET45
Error	98	; expected	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	239	21	MahApps.Metro.NET45
Error	102	; expected	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	247	63	MahApps.Metro.NET45
Error	103	; expected	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	247	64	MahApps.Metro.NET45
Error	105	; expected	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	251	21	MahApps.Metro.NET45
Error	87	Invalid expression term ')'	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	223	65	MahApps.Metro.NET45
Error	94	Invalid expression term ')'	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	235	63	MahApps.Metro.NET45
Error	101	Invalid expression term ')'	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	247	63	MahApps.Metro.NET45
Error	21	Invalid expression term '.'	MahApps.Metro-develop\MahApps.Metro\Controls\WindowCommands.cs	186	61	MahApps.Metro
Error	31	Invalid expression term '.'	MahApps.Metro-develop\MahApps.Metro\Controls\WindowCommands.cs	186	61	MahApps.Metro.NET45
Error	85	Invalid expression term '.'	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	223	34	MahApps.Metro.NET45
Error	92	Invalid expression term '.'	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	235	34	MahApps.Metro.NET45
Error	99	Invalid expression term '.'	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	247	34	MahApps.Metro.NET45
Error	90	Invalid expression term 'else'	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	227	17	MahApps.Metro.NET45
Error	97	Invalid expression term 'else'	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	239	17	MahApps.Metro.NET45
Error	104	Invalid expression term 'else'	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	251	17	MahApps.Metro.NET45
Error	107	Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	223	35	MahApps.Metro.NET45
Error	109	Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	223	61	MahApps.Metro.NET45
Error	110	Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	226	17	MahApps.Metro.NET45
Error	111	Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	235	35	MahApps.Metro.NET45
Error	113	Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	235	59	MahApps.Metro.NET45
Error	114	Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	238	17	MahApps.Metro.NET45
Error	115	Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	247	35	MahApps.Metro.NET45
Error	117	Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	247	59	MahApps.Metro.NET45
Error	118	Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	250	17	MahApps.Metro.NET45
Error	22	Syntax error, ':' expected	MahApps.Metro-develop\MahApps.Metro\Controls\WindowCommands.cs	186	62	MahApps.Metro
Error	32	Syntax error, ':' expected	MahApps.Metro-develop\MahApps.Metro\Controls\WindowCommands.cs	186	62	MahApps.Metro.NET45
Error	86	Syntax error, ':' expected	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	223	35	MahApps.Metro.NET45
Error	93	Syntax error, ':' expected	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	235	35	MahApps.Metro.NET45
Error	100	Syntax error, ':' expected	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	247	35	MahApps.Metro.NET45
Error	3	The member "Resources" is not recognized or is not accessible.	MahApps.Metro-develop\samples\MetroDemo\MainWindow.xaml	33	5	MetroDemo
Error	27	The name 'nameof' does not exist in the current context	MahApps.Metro-develop\paket-files\ControlzEx\ControlzEx\src\ControlzEx\PackIconBase.cs	29	75	MahApps.Metro.NET45
Error	106	The name 'nameof' does not exist in the current context	MahApps.Metro-develop\paket-files\ControlzEx\ControlzEx\src\ControlzEx\PackIconBase.cs	29	75	MahApps.Metro
Error	108	The name 'WindowCloseButtonStyle' does not exist in the current context	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	223	35	MahApps.Metro.NET45
Error	112	The name 'WindowMaxButtonStyle' does not exist in the current context	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	235	35	MahApps.Metro.NET45
Error	116	The name 'WindowMinButtonStyle' does not exist in the current context	MahApps.Metro-develop\MahApps.Metro\Controls\WindowButtonCommands.cs	247	35	MahApps.Metro.NET45
Error	17	The name "CustomValidationPopup" does not exist in the namespace "http://metro.mahapps.com/winfx/xaml/controls".	MahApps.Metro-develop\samples\MetroDemo\App.xaml	1	1	MetroDemo
Error	2	The name "DialogParticipation" does not exist in the namespace "clr-namespace:MahApps.Metro.Controls.Dialogs;assembly=MahApps.Metro".	MahApps.Metro-develop\samples\MetroDemo\MainWindow.xaml	14	23	MetroDemo
Error	16	The name "MetroAnimatedSingleRowTabControl" does not exist in the namespace "clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro".	MahApps.Metro-develop\samples\MetroDemo\MainWindow.xaml	215	13	MetroDemo
Error	8	The name "MetroContentControl" does not exist in the namespace "clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro".	MahApps.Metro-develop\samples\MetroDemo\MainWindow.xaml	144	5	MetroDemo
Error	1	The name "MetroWindow" does not exist in the namespace "clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro".	MahApps.Metro-develop\samples\MetroDemo\MainWindow.xaml	1	1	MetroDemo
Error	4	The name "MetroWindow" does not exist in the namespace "clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro".	MahApps.Metro-develop\samples\MetroDemo\MainWindow.xaml	96	5	MetroDemo
Error	6	The name "MetroWindow" does not exist in the namespace "clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro".	MahApps.Metro-develop\samples\MetroDemo\MainWindow.xaml	110	5	MetroDemo
Error	9	The name "MetroWindow" does not exist in the namespace "clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro".	MahApps.Metro-develop\samples\MetroDemo\MainWindow.xaml	166	31	MetroDemo
Error	10	The name "MetroWindow" does not exist in the namespace "clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro".	MahApps.Metro-develop\samples\MetroDemo\MainWindow.xaml	189	31	MetroDemo
Error	11	The name "MetroWindow" does not exist in the namespace "clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro".	MahApps.Metro-develop\samples\MetroDemo\MainWindow.xaml	192	31	MetroDemo
Error	12	The name "MetroWindow" does not exist in the namespace "clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro".	MahApps.Metro-develop\samples\MetroDemo\MainWindow.xaml	195	31	MetroDemo
Error	13	The name "MetroWindow" does not exist in the namespace "clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro".	MahApps.Metro-develop\samples\MetroDemo\MainWindow.xaml	198	31	MetroDemo
Error	14	The name "MetroWindow" does not exist in the namespace "clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro".	MahApps.Metro-develop\samples\MetroDemo\MainWindow.xaml	207	31	MetroDemo
Error	15	The name "MetroWindow" does not exist in the namespace "clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro".	MahApps.Metro-develop\samples\MetroDemo\MainWindow.xaml	210	31	MetroDemo
Error	5	The name "WindowCommands" does not exist in the namespace "clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro".	MahApps.Metro-develop\samples\MetroDemo\MainWindow.xaml	97	9	MetroDemo
Error	7	The name "WindowCommands" does not exist in the namespace "clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro".	MahApps.Metro-develop\samples\MetroDemo\MainWindow.xaml	111	9	MetroDemo
Error	48	The property 'ControlsHelper.HeaderFontSize' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/controls'. Line 27 Position 34.	MahApps.Metro-develop\samples\MetroDemo\ExampleViews\TabControlExamples.xaml	27	34	MetroDemo
Error	70	The property 'ControlsHelper.HeaderFontSize' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/controls'. Line 27 Position 34.	MahApps.Metro-develop\samples\MetroDemo\ExampleViews\TabControlExamples.xaml	27	34	MetroDemo.NET45
Error	46	The property 'TextBoxHelper.ClearTextButton' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/controls'. Line 123 Position 27.	MahApps.Metro-develop\samples\MetroDemo\ExampleViews\SelectionExamples.xaml	123	27	MetroDemo
Error	68	The property 'TextBoxHelper.ClearTextButton' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/controls'. Line 123 Position 27.	MahApps.Metro-develop\samples\MetroDemo\ExampleViews\SelectionExamples.xaml	123	27	MetroDemo.NET45
Error	49	The property 'TextBoxHelper.IsSpellCheckContextMenuEnabled' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/controls'. Line 43 Position 26.	MahApps.Metro-develop\samples\MetroDemo\ExampleViews\TextExamples.xaml	43	26	MetroDemo
Error	71	The property 'TextBoxHelper.IsSpellCheckContextMenuEnabled' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/controls'. Line 43 Position 26.	MahApps.Metro-develop\samples\MetroDemo\ExampleViews\TextExamples.xaml	43	26	MetroDemo.NET45
Error	83	The property 'TextBoxHelper.Watermark' does not exist in XML namespace 'clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro'. Line 25 Position 26.	MahApps.Metro-develop\samples\Caliburn.Metro.Demo\Views\Flyouts\Flyout1View.xaml	25	26	Caliburn.Metro.Demo
Error	44	The property 'TextBoxHelper.Watermark' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/controls'. Line 38 Position 29.	MahApps.Metro-develop\samples\MetroDemo\ExampleViews\DateExamples.xaml	38	29	MetroDemo
Error	66	The property 'TextBoxHelper.Watermark' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/controls'. Line 38 Position 29.	MahApps.Metro-develop\samples\MetroDemo\ExampleViews\DateExamples.xaml	38	29	MetroDemo.NET45
Error	42	The tag 'BindableResourceBehavior' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/shared'. Line 46 Position 34.	MahApps.Metro-develop\samples\MetroDemo\ExampleViews\ColorExample.xaml	46	34	MetroDemo
Error	64	The tag 'BindableResourceBehavior' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/shared'. Line 46 Position 34.	MahApps.Metro-develop\samples\MetroDemo\ExampleViews\ColorExample.xaml	46	34	MetroDemo.NET45
Error	43	The tag 'DataGridNumericUpDownColumn' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/controls'. Line 150 Position 18.	MahApps.Metro-develop\samples\MetroDemo\ExampleViews\DataGridExamples.xaml	150	18	MetroDemo
Error	65	The tag 'DataGridNumericUpDownColumn' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/controls'. Line 150 Position 18.	MahApps.Metro-develop\samples\MetroDemo\ExampleViews\DataGridExamples.xaml	150	18	MetroDemo.NET45
Error	40	The tag 'Flyout' does not exist in XML namespace 'clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro'. Line 1 Position 18.	MahApps.Metro-develop\samples\MetroDemo\ExampleWindows\CustomFlyout.xaml	1	18	MetroDemo
Error	74	The tag 'Flyout' does not exist in XML namespace 'clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro'. Line 1 Position 18.	MahApps.Metro-develop\samples\MetroDemo\ExampleWindows\CustomFlyout.xaml	1	18	MetroDemo.NET45
Error	54	The tag 'Flyout' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/controls'. Line 1 Position 18.	MahApps.Metro-develop\samples\MetroDemo\ExampleWindows\DynamicFlyout.xaml	1	18	MetroDemo
Error	75	The tag 'Flyout' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/controls'. Line 1 Position 18.	MahApps.Metro-develop\samples\MetroDemo\ExampleWindows\DynamicFlyout.xaml	1	18	MetroDemo.NET45
Error	39	The tag 'MetroWindow' does not exist in XML namespace 'clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro'. Line 1 Position 23.	MahApps.Metro-develop\samples\MetroDemo\ExampleWindows\CleanWindowDemo.xaml	1	23	MetroDemo
Error	50	The tag 'MetroWindow' does not exist in XML namespace 'clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro'. Line 1 Position 23.	MahApps.Metro-develop\samples\MetroDemo\ExampleWindows\FlyoutDemo.xaml	1	23	MetroDemo
Error	51	The tag 'MetroWindow' does not exist in XML namespace 'clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro'. Line 1 Position 23.	MahApps.Metro-develop\samples\MetroDemo\ExampleWindows\IconsWindow.xaml	1	23	MetroDemo
Error	52	The tag 'MetroWindow' does not exist in XML namespace 'clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro'. Line 1 Position 23.	MahApps.Metro-develop\samples\MetroDemo\ExampleWindows\InteropDemo.xaml	1	23	MetroDemo
Error	53	The tag 'MetroWindow' does not exist in XML namespace 'clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro'. Line 1 Position 23.	MahApps.Metro-develop\samples\MetroDemo\ExampleWindows\SizeToContentDemo.xaml	1	23	MetroDemo
Error	55	The tag 'MetroWindow' does not exist in XML namespace 'clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro'. Line 1 Position 23.	MahApps.Metro-develop\samples\MetroDemo\MainWindow.xaml	1	23	MetroDemo
Error	56	The tag 'MetroWindow' does not exist in XML namespace 'clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro'. Line 1 Position 23.	MahApps.Metro-develop\samples\MetroDemo\ExampleWindows\VSDemo.xaml	1	23	MetroDemo
Error	73	The tag 'MetroWindow' does not exist in XML namespace 'clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro'. Line 1 Position 23.	MahApps.Metro-develop\samples\MetroDemo\ExampleWindows\CleanWindowDemo.xaml	1	23	MetroDemo.NET45
Error	76	The tag 'MetroWindow' does not exist in XML namespace 'clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro'. Line 1 Position 23.	MahApps.Metro-develop\samples\MetroDemo\ExampleWindows\FlyoutDemo.xaml	1	23	MetroDemo.NET45
Error	78	The tag 'MetroWindow' does not exist in XML namespace 'clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro'. Line 1 Position 23.	MahApps.Metro-develop\samples\MetroDemo\ExampleWindows\IconsWindow.xaml	1	23	MetroDemo.NET45
Error	79	The tag 'MetroWindow' does not exist in XML namespace 'clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro'. Line 1 Position 23.	MahApps.Metro-develop\samples\MetroDemo\ExampleWindows\InteropDemo.xaml	1	23	MetroDemo.NET45
Error	80	The tag 'MetroWindow' does not exist in XML namespace 'clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro'. Line 1 Position 23.	MahApps.Metro-develop\samples\MetroDemo\ExampleWindows\SizeToContentDemo.xaml	1	23	MetroDemo.NET45
Error	81	The tag 'MetroWindow' does not exist in XML namespace 'clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro'. Line 1 Position 23.	MahApps.Metro-develop\samples\MetroDemo\ExampleWindows\VSDemo.xaml	1	23	MetroDemo.NET45
Error	82	The tag 'MetroWindow' does not exist in XML namespace 'clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro'. Line 1 Position 23.	MahApps.Metro-develop\samples\MetroDemo\MainWindow.xaml	1	23	MetroDemo.NET45
Error	84	The tag 'MetroWindow' does not exist in XML namespace 'clr-namespace:MahApps.Metro.Controls;assembly=MahApps.Metro'. Line 1 Position 23.	MahApps.Metro-develop\samples\Caliburn.Metro.Demo\Views\ShellView.xaml	1	23	Caliburn.Metro.Demo
Error	57	The tag 'MetroWindow' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/controls'. Line 1 Position 23.	MahApps.Metro-develop\Mahapps.Metro.Tests\CleanWindow.xaml	1	23	Mahapps.Metro.Tests
Error	58	The tag 'MetroWindow' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/controls'. Line 1 Position 23.	MahApps.Metro-develop\Mahapps.Metro.Tests\DialogWindow.xaml	1	23	Mahapps.Metro.Tests
Error	59	The tag 'MetroWindow' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/controls'. Line 1 Position 23.	MahApps.Metro-develop\Mahapps.Metro.Tests\ButtonWindow.xaml	1	23	Mahapps.Metro.Tests
Error	60	The tag 'MetroWindow' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/controls'. Line 1 Position 23.	MahApps.Metro-develop\Mahapps.Metro.Tests\HiddenMinMaxCloseButtonsWindow.xaml	1	23	Mahapps.Metro.Tests
Error	61	The tag 'MetroWindow' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/controls'. Line 1 Position 23.	MahApps.Metro-develop\Mahapps.Metro.Tests\FlyoutWindow.xaml	1	23	Mahapps.Metro.Tests
Error	77	The tag 'MetroWindow' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/controls'. Line 1 Position 23.	MahApps.Metro-develop\samples\MetroDemo\ExampleWindows\IconPacksWindow.xaml	1	23	MetroDemo.NET45
Error	47	The tag 'RangeSlider' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/controls'. Line 82 Position 18.	MahApps.Metro-develop\samples\MetroDemo\ExampleViews\SliderProgressExamples.xaml	82	18	MetroDemo
Error	69	The tag 'RangeSlider' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/controls'. Line 82 Position 18.	MahApps.Metro-develop\samples\MetroDemo\ExampleViews\SliderProgressExamples.xaml	82	18	MetroDemo.NET45
Error	37	The type reference cannot find a public type named 'CustomValidationPopup'. Line 23 Position 121.	MahApps.Metro-develop\samples\MetroDemo\App.xaml	23	121	MetroDemo
Error	62	The type reference cannot find a public type named 'CustomValidationPopup'. Line 23 Position 121.	MahApps.Metro-develop\samples\MetroDemo\App.xaml	23	121	MetroDemo.NET45
Error	38	The type reference cannot find a public type named 'Tile'. Line 17 Position 70.	MahApps.Metro-develop\samples\MetroDemo\ExampleViews\TilesExample.xaml	17	70	MetroDemo
Error	72	The type reference cannot find a public type named 'Tile'. Line 17 Position 70.	MahApps.Metro-develop\samples\MetroDemo\ExampleViews\TilesExample.xaml	17	70	MetroDemo.NET45
Error	41	The type reference cannot find a public type named 'ToggleSwitch'. Line 162 Position 68.	MahApps.Metro-develop\samples\MetroDemo\ExampleViews\ButtonsExample.xaml	162	68	MetroDemo
Error	63	The type reference cannot find a public type named 'ToggleSwitch'. Line 162 Position 68.	MahApps.Metro-develop\samples\MetroDemo\ExampleViews\ButtonsExample.xaml	162	68	MetroDemo.NET45
Error	45	The type reference cannot find a public type named 'TransitioningContentControl'. Line 20 Position 152.	MahApps.Metro-develop\samples\MetroDemo\ExampleViews\OtherExamples.xaml	20	152	MetroDemo
Error	67	The type reference cannot find a public type named 'TransitioningContentControl'. Line 20 Position 152.	MahApps.Metro-develop\samples\MetroDemo\ExampleViews\OtherExamples.xaml	20	152	MetroDemo.NET45

**Comment by punker76** [comment]
@vipinnair you need min VS 2015 Community Ed. to compile the dev branch -> https://github.com/MahApps/MahApps.Metro#contributing-to-this-project

**Comment by vipinnair** [comment]
oh ok. I was using VS 2013. Thanks

**Pull request merged**
