### PR TITLE
Add a ColorPicker-Control

### LINKED ISSUE #3520: ColorPicker Control
**Is your feature request related to a problem? Please describe.**
I wanted to give my users the option to hava a custom accent color. My result is a custom class for now, but may be someday it will be implemented for others, too. ( see #3515 ). I think it would be nice to have a colorpicker, as there is none in WPF by default

**Describe the solution you'd like**
have a colorpicker for selecting colors

**Additional context**
There are several ideas what we can do:
* make a custom controltemplate for this one: https://github.com/xceedsoftware/wpftoolkit/wiki/ColorPicker 
* make a new control similar to this colorpicker https://github.com/xceedsoftware/wpftoolkit/wiki/ColorPicker (I don't know if we are allowed to take code from there)
* Create a now control from scratch

**Closed Issues**
None 

@punker76 I would like to help with this topic, if you want me to. If you don't want to have a colorpicker at all, just close this issue. I wont blame you.

### LINKED ISSUE #3920: Colorpicker
It would be awesome if someone could created (or already has created) a color picker in the MahApps style. Including some color converters Getting and Settings a Color or brush. Currently i'm using one from Xceed WPF Toolkit which is nice but it stands out that it's not the same theme as the rest of the application.

### PR DESCRIPTION
**Pull request by timunie**
## Describe the changes you have made to improve this project

- Added a `ColorEyeDropper` - Control: The user can pick a color from the screen
- Added a `ColorPalette` - Control: The user can select any predefined color
- Added a `ColorCanvas` - Control: The user can create any color by providing either `ARGB` or `AHSV`
- Added a `ColorPicker` - Control: All above controls connected

## Additional context

A cleaned version of this PR: #3710 

## The control in action 

mahapps_colorpicker2

## Closed Issues

Closes #3920 
Closes #3520 
Closes #3710

### CODE REVIEW

**Comment by AKruimink** [comment]
Question, potentialy unrelated to the color picker (nice job btw), when you change the color in the gif to green the text in the application jumps to black, but the header text of the color picker control stays white, did you by any change miss setting the text color dynamicly?

**Review by punker76 — COMMENTED** [review]
LGTM 👍

**Comment by punker76** [comment]
@timunie your changes have been merged, thanks for your contribution 👍

It would be nice that you also write the documentation for this new stuff at the doc repo ;-)

**Comment by seba30** [comment]
Hey there,

I use the ColorCanvas to adjust the LED color on our devices. Sadly I can't find a DP (or maybe I'm too stupid) to disable the following:

- Alpha channel (makes no sense here in my case)
- HSV
- Name

It would be great, if you plan to develop and integrate these features in the future.

Thank you!

**Comment by punker76** [comment]
@seba30 I had the same idea, but didn't create an issue for it. So it would be nice if you can create one :-D

**Comment by seba30** [comment]
Issue #4020

**Pull request merged**
