### PR TITLE
Fix for IgnoreTaskbarOnMaximize issue

### PR DESCRIPTION
**Pull request by igorushi**
## Fix for IgnoreTaskbarOnMaximize issue
_2618_

### CODE REVIEW

**Comment by punker76** [comment]
@igorushi Thx, this work work around works for me too (it flickers now a little bit on maxmize). But can you take my last changes to your changes? Thx.

**Comment by igorushi** [comment]
@punker76 sure, what changes have I missed?

**Comment by punker76** [comment]
@igorushi Your dev branch is not upd to date, here my latest commit from yesterday ab013bd5c30c54ae7912ae81ac033b1bf99173e0

**Comment by igorushi** [comment]
done.

**Comment by igorushi** [comment]
@punker76 , could you please merge this commit [fe46320](https://github.com/igorushi/MahApps.Metro/commit/fe46320aa5c633390320ff0f50a36d6e30d34c70)

**Comment by punker76** [comment]
@igorushi Done and available with 191 alpha. I can say that it works. I changed my full screen sample to test it out https://github.com/punker76/code-samples/tree/master/MahAppsMetroFullScreen

**Pull request merged**
