### PR TITLE
[RFC] Adds an attached property for scrollbar

### PR DESCRIPTION
**Pull request by Evangelink**
## What changed?

This attached property allows to trigger the call to a command when reaching the end of the scrollable area. You can use it for example to create a lazy loading and load more items when the user reach the end of the list.

See #2615

### CODE REVIEW

**Comment by kamilkosek** [comment]
Hi,
was looking at it and found a small (maybe copy&paste) typo:
I.e. line 38 :
` public static readonly DependencyProperty EndOfScrollReadchedCommandProperty =` 
but should be 
` public static readonly DependencyProperty EndOfScrollReachedCommandProperty =`

**Comment by Evangelink** [comment]
Hi @kamilkosek! Thanks for this, I will try to fix it as soon as possible!

**Comment by avechuche** [comment]
@Evangelink Hello! Is this implemented? I can not use it. Thx!

**Comment by Evangelink** [comment]
Hi @kamilkosek I made the change (sorry for having been so late).
Hi @avechuche this is implemented in this PR but as you can see this is not merged hence not available on the release MahApps.

@punker76 Were you waiting for something else than a rebase of the PR? Not sure what RFC means.

Cheers,
Amaury

**Pull request closed without merging**
