### PR TITLE
Change the VisibilityHelper to handle the DataGridColumn visibility

### PR DESCRIPTION
**Pull request by fredericoregateiro**
## Describe the changes you have made to improve this project

The VisibilityHelper cannot change the visibility of a DataGridColumn, this type does not inherits from FrameworkElement.
I've update the VisibilityHelper to allow this case.

I also updated the sample project to show this feature in use, in the DataGrid view.

### CODE REVIEW

**Comment by fredericoregateiro** [comment]
When changing the DataGridColumn visibility, there are some binding errors happening.

See discussion #4232

**Comment by punker76** [comment]
@fredericoregateiro It seems like that your last commit was for a different issue?

**Comment by fredericoregateiro** [comment]
@punker76 yes, i created other to solve #4245.
I thought the merge was completed and i deleted that fork, do you need another PR?

**Comment by punker76** [comment]
@fredericoregateiro sorry for this, no I didn't merged it, but want it to to. Can you create a new PR with only this visibility change? Thx 🙏🏻

**Comment by fredericoregateiro** [comment]
@punker76  I apologize, it was my inexperience creating PR's, i commited 2 diferent changes into the same branch.
So i think it's better if i delete my fork, create a new one and commit my changes to separated branches.

**Pull request closed without merging**
