### PR TITLE
Add IsVisible property to HambugerMenuItemBase

### LINKED ISSUE #3768: Toggling visibility on hamburger menu
It would be nice to have a visibility open on hamburger menu items to hide from people that are not suppose to see instead of just it being disabled for certain users.

### PR DESCRIPTION
**Pull request by bNobo**
I've added a Visibility property to HamburgerMenuItem and HamburgerMenuSeparatorItem in response to issue #3768 

**Closed Issues**
It will closes #3768

### CODE REVIEW

**Comment by timunie** [comment]
Hi @bNobo ,

is there a reason you did not implement this in the base class? I am sorry if you got me wrong, I wanted to confirm your first idea.

**Comment by bNobo** [comment]
Hi @timunie ,

you're absolutely right, I'll move the property to the base class to avoid duplication. I've also realized I forgot to update the template of other `HamburgerMenuItemBase` descendants like `HamburgerMenuHeaderItem`. I will fix that too.

**Comment by bNobo** [comment]
Everything should be OK now, Visibility property works for every `HamburgerMenuItemBase` descendants. Feel free to make me know if I still can improve the code in any way.

**Comment by punker76** [comment]
@bNobo your changes have been merged, thanks for your contribution 👍

I've changed the property from Visibility to IsVisible. IMO IsVisible is the better way to say if an item should be shown or not. With the Visibility property you can set an item also to hide which means that the item is only hidden.

**Pull request merged**
