### PR TITLE
CheckBox Windows 10 Style

### LINKED ISSUE #3136: Checkbox colors on dark theme arent good
Below is a screenshot of the demo showing the default white theme and dark puple. As you can see the checkbox on white theme is okay but on dark theme hardly seeable because the purple color is too dark. Same problem with lots of other colors on dark theme. I don't think this issue needs a sample as you can reproduce this in a second on the demo app.

theme

//edit: For some reasons I've noticed the color on checkboxes are different than the color used on other controls:

theme2

### PR DESCRIPTION
**Pull request by timunie**
**Describe the changes you have made to improve this project**

Added a `CheckBoxHelper` to enable different `CheckBox `designs. Thanks to this helper class I created a style similar to the UWP `CheckBox`.

The main advantage of this approach is, that it is not a breaking change, unless the new style is the default style. Moreover the user can create `CheckBoxStyles` on his own, e.g. an eye for `Visibility`. 

**Additional context**

Sample XAML:
```
            <CheckBox Margin="{StaticResource ControlMargin}"
                      Content="Enabled"
                      IsChecked="True" />
            <CheckBox Margin="{StaticResource ControlMargin}"
                      Content="Windows 10 Style"
                      IsChecked="{x:Null}"
                      IsThreeState="True" 
                      Style="{StaticResource MahApps.Metro.Styles.CheckBox.Win10}"/>
            <CheckBox Margin="{StaticResource ControlMargin}"
                      Content="This is a custom Glyph in a rounded CheckBox"
                      IsEnabled="True"
                      BorderThickness="2"
                      Controls:CheckBoxHelper.CheckedBorderBrush="DarkRed"
                      Controls:CheckBoxHelper.CheckedBackgroundBrush="LightGreen"
                      Controls:CheckBoxHelper.CheckBoxSize="40"
                      Controls:ControlsHelper.CornerRadius ="15">
                <Controls:CheckBoxHelper.CheckedGlyphTemplate>
                    <DataTemplate>
                        <iconPacks:PackIconFontAwesome Kind="EyeSolid" 
                                                       Width="30"  
                                                       Height="30" 
                                                       Foreground="DarkGreen" 
                                                       HorizontalAlignment="Center" 
                                                       VerticalAlignment="Center"/>
                    </DataTemplate>
                </Controls:CheckBoxHelper.CheckedGlyphTemplate>
            </CheckBox>
```

image

image

**Closed Issues**

Closes #3136

### CODE REVIEW

**Comment by timunie** [comment]
@punker76 In Win10 the Checkbox size is 20x20 px, in MahApps it is 18x18 px. What do you think, which value should we use as default for this style?

**Comment by Nuklon** [comment]
> @punker76 In Win10 the Checkbox size is 20x20 px, in MahApps it is 18x18 px. What do you think, which value should we use as default for this style?
W10 style should use W10 size I think, so 20x20.

**Comment by punker76** [comment]
2020-01-06_22h25_19

2020-01-06_22h25_34

## Colors and Brushes taken from Win10 UWP

### New Colors

MahApps.Colors.SystemAccent
MahApps.Colors.SystemAltHigh
MahApps.Colors.SystemAltLow
MahApps.Colors.SystemAltMedium
MahApps.Colors.SystemAltMediumHigh
MahApps.Colors.SystemAltMediumLow
MahApps.Colors.SystemBaseHigh
MahApps.Colors.SystemBaseLow
MahApps.Colors.SystemBaseMedium
MahApps.Colors.SystemBaseMediumHigh
MahApps.Colors.SystemBaseMediumLow
MahApps.Colors.SystemChromeAltLow
MahApps.Colors.SystemChromeBlackHigh
MahApps.Colors.SystemChromeBlackLow
MahApps.Colors.SystemChromeBlackMediumLow
MahApps.Colors.SystemChromeBlackMedium
MahApps.Colors.SystemChromeDisabledHigh
MahApps.Colors.SystemChromeDisabledLow
MahApps.Colors.SystemChromeHigh
MahApps.Colors.SystemChromeLow
MahApps.Colors.SystemChromeMedium
MahApps.Colors.SystemChromeMediumLow
MahApps.Colors.SystemChromeWhite
MahApps.Colors.SystemChromeGray
MahApps.Colors.SystemListLow
MahApps.Colors.SystemListMedium
MahApps.Colors.SystemErrorText

### New Brushes

MahApps.Brushes.SystemControlBackgroundAccent
MahApps.Brushes.SystemControlBackgroundAltHigh
MahApps.Brushes.SystemControlBackgroundAltMediumHigh
MahApps.Brushes.SystemControlBackgroundAltMedium
MahApps.Brushes.SystemControlBackgroundAltMediumLow
MahApps.Brushes.SystemControlBackgroundBaseHigh
MahApps.Brushes.SystemControlBackgroundBaseLow
MahApps.Brushes.SystemControlBackgroundBaseMedium
MahApps.Brushes.SystemControlBackgroundBaseMediumHigh
MahApps.Brushes.SystemControlBackgroundBaseMediumLow
MahApps.Brushes.SystemControlBackgroundChromeBlackHigh
MahApps.Brushes.SystemControlBackgroundChromeBlackMedium
MahApps.Brushes.SystemControlBackgroundChromeBlackLow
MahApps.Brushes.SystemControlBackgroundChromeBlackMediumLow
MahApps.Brushes.SystemControlBackgroundChromeMedium
MahApps.Brushes.SystemControlBackgroundChromeMediumLow
MahApps.Brushes.SystemControlBackgroundChromeWhite
MahApps.Brushes.SystemControlBackgroundListLow
MahApps.Brushes.SystemControlBackgroundListMedium
MahApps.Brushes.SystemControlDisabledAccent
MahApps.Brushes.SystemControlDisabledBaseHigh
MahApps.Brushes.SystemControlDisabledBaseLow
MahApps.Brushes.SystemControlDisabledBaseMediumLow
MahApps.Brushes.SystemControlDisabledChromeDisabledHigh
MahApps.Brushes.SystemControlDisabledChromeDisabledLow
MahApps.Brushes.SystemControlDisabledChromeHigh
MahApps.Brushes.SystemControlDisabledChromeMediumLow
MahApps.Brushes.SystemControlDisabledListMedium
MahApps.Brushes.SystemControlDisabledTransparent
MahApps.Brushes.SystemControlFocusVisualPrimary
MahApps.Brushes.SystemControlFocusVisualSecondary
MahApps.Brushes.SystemControlRevealFocusVisual
MahApps.Brushes.SystemControlForegroundAccent
MahApps.Brushes.SystemControlForegroundAltHigh
MahApps.Brushes.SystemControlForegroundAltMediumHigh
MahApps.Brushes.SystemControlForegroundBaseHigh
MahApps.Brushes.SystemControlForegroundBaseLow
MahApps.Brushes.SystemControlForegroundBaseMedium
MahApps.Brushes.SystemControlForegroundBaseMediumHigh
MahApps.Brushes.SystemControlForegroundBaseMediumLow
MahApps.Brushes.SystemControlForegroundChromeBlackHigh
MahApps.Brushes.SystemControlForegroundChromeHigh
MahApps.Brushes.SystemControlForegroundChromeMedium
MahApps.Brushes.SystemControlForegroundChromeWhite
MahApps.Brushes.SystemControlForegroundChromeDisabledLow
MahApps.Brushes.SystemControlForegroundChromeGray
MahApps.Brushes.SystemControlForegroundListLow
MahApps.Brushes.SystemControlForegroundListMedium
MahApps.Brushes.SystemControlForegroundTransparent
MahApps.Brushes.SystemControlForegroundChromeBlackMedium
MahApps.Brushes.SystemControlForegroundChromeBlackMediumLow
MahApps.Brushes.SystemControlHighlightAccent
MahApps.Brushes.SystemControlHighlightAltAccent
MahApps.Brushes.SystemControlHighlightAltAltHigh
MahApps.Brushes.SystemControlHighlightAltBaseHigh
MahApps.Brushes.SystemControlHighlightAltBaseLow
MahApps.Brushes.SystemControlHighlightAltBaseMedium
MahApps.Brushes.SystemControlHighlightAltBaseMediumHigh
MahApps.Brushes.SystemControlHighlightAltAltMediumHigh
MahApps.Brushes.SystemControlHighlightAltBaseMediumLow
MahApps.Brushes.SystemControlHighlightAltListAccentHigh
MahApps.Brushes.SystemControlHighlightAltListAccentLow
MahApps.Brushes.SystemControlHighlightAltListAccentMedium
MahApps.Brushes.SystemControlHighlightAltChromeWhite
MahApps.Brushes.SystemControlHighlightAltTransparent
MahApps.Brushes.SystemControlHighlightBaseHigh
MahApps.Brushes.SystemControlHighlightBaseLow
MahApps.Brushes.SystemControlHighlightBaseMedium
MahApps.Brushes.SystemControlHighlightBaseMediumHigh
MahApps.Brushes.SystemControlHighlightBaseMediumLow
MahApps.Brushes.SystemControlHighlightChromeAltLow
MahApps.Brushes.SystemControlHighlightChromeHigh
MahApps.Brushes.SystemControlHighlightListAccentHigh
MahApps.Brushes.SystemControlHighlightListAccentLow
MahApps.Brushes.SystemControlHighlightListAccentMedium
MahApps.Brushes.SystemControlHighlightListMedium
MahApps.Brushes.SystemControlHighlightListLow
MahApps.Brushes.SystemControlHighlightChromeWhite
MahApps.Brushes.SystemControlHighlightTransparent
MahApps.Brushes.SystemControlHyperlinkText
MahApps.Brushes.SystemControlHyperlinkBaseHigh
MahApps.Brushes.SystemControlHyperlinkBaseMedium
MahApps.Brushes.SystemControlHyperlinkBaseMediumHigh
MahApps.Brushes.SystemControlPageBackgroundAltMedium
MahApps.Brushes.SystemControlPageBackgroundAltHigh
MahApps.Brushes.SystemControlPageBackgroundMediumAltMedium
MahApps.Brushes.SystemControlPageBackgroundBaseLow
MahApps.Brushes.SystemControlPageBackgroundBaseMedium
MahApps.Brushes.SystemControlPageBackgroundListLow
MahApps.Brushes.SystemControlPageBackgroundChromeLow
MahApps.Brushes.SystemControlPageBackgroundChromeMediumLow
MahApps.Brushes.SystemControlPageBackgroundTransparent
MahApps.Brushes.SystemControlPageTextBaseHigh
MahApps.Brushes.SystemControlPageTextBaseMedium
MahApps.Brushes.SystemControlPageTextChromeBlackMediumLow
MahApps.Brushes.SystemControlTransparent
MahApps.Brushes.SystemControlErrorTextForeground
MahApps.Brushes.SystemControlTransientBorder

### New CheckBox Brushes

MahApps.Brushes.CheckBox.ForegroundUnchecked
MahApps.Brushes.CheckBox.ForegroundUncheckedMouseOver
MahApps.Brushes.CheckBox.ForegroundUncheckedPressed
MahApps.Brushes.CheckBox.ForegroundUncheckedDisabled
MahApps.Brushes.CheckBox.ForegroundChecked
MahApps.Brushes.CheckBox.ForegroundCheckedMouseOver
MahApps.Brushes.CheckBox.ForegroundCheckedPressed
MahApps.Brushes.CheckBox.ForegroundCheckedDisabled
MahApps.Brushes.CheckBox.ForegroundIndeterminate
MahApps.Brushes.CheckBox.ForegroundIndeterminateMouseOver
MahApps.Brushes.CheckBox.ForegroundIndeterminatePressed
MahApps.Brushes.CheckBox.ForegroundIndeterminateDisabled
MahApps.Brushes.CheckBox.BackgroundUnchecked
MahApps.Brushes.CheckBox.BackgroundUncheckedMouseOver
MahApps.Brushes.CheckBox.BackgroundUncheckedPressed
MahApps.Brushes.CheckBox.BackgroundUncheckedDisabled
MahApps.Brushes.CheckBox.BackgroundChecked
MahApps.Brushes.CheckBox.BackgroundCheckedMouseOver
MahApps.Brushes.CheckBox.BackgroundCheckedPressed
MahApps.Brushes.CheckBox.BackgroundCheckedDisabled
MahApps.Brushes.CheckBox.BackgroundIndeterminate
MahApps.Brushes.CheckBox.BackgroundIndeterminateMouseOver
MahApps.Brushes.CheckBox.BackgroundIndeterminatePressed
MahApps.Brushes.CheckBox.BackgroundIndeterminateDisabled
MahApps.Brushes.CheckBox.BorderBrushUnchecked
MahApps.Brushes.CheckBox.BorderBrushUncheckedMouseOver
MahApps.Brushes.CheckBox.BorderBrushUncheckedPressed
MahApps.Brushes.CheckBox.BorderBrushUncheckedDisabled
MahApps.Brushes.CheckBox.BorderBrushChecked
MahApps.Brushes.CheckBox.BorderBrushCheckedMouseOver
MahApps.Brushes.CheckBox.BorderBrushCheckedPressed
MahApps.Brushes.CheckBox.BorderBrushCheckedDisabled
MahApps.Brushes.CheckBox.BorderBrushIndeterminate
MahApps.Brushes.CheckBox.BorderBrushIndeterminateMouseOver
MahApps.Brushes.CheckBox.BorderBrushIndeterminatePressed
MahApps.Brushes.CheckBox.BorderBrushIndeterminateDisabled
MahApps.Brushes.CheckBox.CheckBorderBrushUnchecked
MahApps.Brushes.CheckBox.CheckBorderBrushUncheckedMouseOver
MahApps.Brushes.CheckBox.CheckBorderBrushUncheckedPressed
MahApps.Brushes.CheckBox.CheckBorderBrushUncheckedDisabled
MahApps.Brushes.CheckBox.CheckBorderBrushChecked
MahApps.Brushes.CheckBox.CheckBorderBrushCheckedMouseOver
MahApps.Brushes.CheckBox.CheckBorderBrushCheckedPressed
MahApps.Brushes.CheckBox.CheckBorderBrushCheckedDisabled
MahApps.Brushes.CheckBox.CheckBorderBrushIndeterminate
MahApps.Brushes.CheckBox.CheckBorderBrushIndeterminateMouseOver
MahApps.Brushes.CheckBox.CheckBorderBrushIndeterminatePressed
MahApps.Brushes.CheckBox.CheckBorderBrushIndeterminateDisabled
MahApps.Brushes.CheckBox.CheckBackgroundUnchecked
MahApps.Brushes.CheckBox.CheckBackgroundUncheckedMouseOver
MahApps.Brushes.CheckBox.CheckBackgroundUncheckedPressed
MahApps.Brushes.CheckBox.CheckBackgroundUncheckedDisabled
MahApps.Brushes.CheckBox.CheckBackgroundChecked
MahApps.Brushes.CheckBox.CheckBackgroundCheckedMouseOver
MahApps.Brushes.CheckBox.CheckBackgroundCheckedPressed
MahApps.Brushes.CheckBox.CheckBackgroundCheckedDisabled
MahApps.Brushes.CheckBox.CheckBackgroundIndeterminate
MahApps.Brushes.CheckBox.CheckBackgroundIndeterminateMouseOver
MahApps.Brushes.CheckBox.CheckBackgroundIndeterminatePressed
MahApps.Brushes.CheckBox.CheckBackgroundIndeterminateDisabled
MahApps.Brushes.CheckBox.CheckGlyphForegroundUnchecked
MahApps.Brushes.CheckBox.CheckGlyphForegroundUncheckedMouseOver
MahApps.Brushes.CheckBox.CheckGlyphForegroundUncheckedPressed
MahApps.Brushes.CheckBox.CheckGlyphForegroundUncheckedDisabled
MahApps.Brushes.CheckBox.CheckGlyphForegroundChecked
MahApps.Brushes.CheckBox.CheckGlyphForegroundCheckedMouseOver
MahApps.Brushes.CheckBox.CheckGlyphForegroundCheckedPressed
MahApps.Brushes.CheckBox.CheckGlyphForegroundCheckedDisabled
MahApps.Brushes.CheckBox.CheckGlyphForegroundIndeterminate
MahApps.Brushes.CheckBox.CheckGlyphForegroundIndeterminateMouseOver
MahApps.Brushes.CheckBox.CheckGlyphForegroundIndeterminatePressed
MahApps.Brushes.CheckBox.CheckGlyphForegroundIndeterminateDisabled

## New CheckBoxHelper attached properties

CheckSize
CheckBorderThickness
CheckGlyphUnchecked
CheckGlyphUncheckedTemplate
ForegroundUnchecked
BackgroundUnchecked
BorderBrushUnchecked
CheckBackgroundUnchecked
CheckBorderBrushUnchecked
CheckGlyphForegroundUnchecked
ForegroundUncheckedMouseOver
BackgroundUncheckedMouseOver
BorderBrushUncheckedMouseOver
CheckBackgroundUncheckedMouseOver
CheckBorderBrushUncheckedMouseOver
CheckGlyphForegroundUncheckedMouseOver
ForegroundUncheckedPressed
BackgroundUncheckedPressed
BorderBrushUncheckedPressed
CheckBackgroundUncheckedPressed
CheckBorderBrushUncheckedPressed
CheckGlyphForegroundUncheckedPressed
ForegroundUncheckedDisabled
BackgroundUncheckedDisabled
BorderBrushUncheckedDisabled
CheckBackgroundUncheckedDisabled
CheckBorderBrushUncheckedDisabled
CheckGlyphForegroundUncheckedDisabled
CheckGlyphCheckedTemplate
ForegroundChecked
BackgroundChecked
BorderBrushChecked
CheckBackgroundChecked
CheckBorderBrushChecked
CheckGlyphForegroundChecked
ForegroundCheckedMouseOver
BackgroundCheckedMouseOver
BorderBrushCheckedMouseOver
CheckBackgroundCheckedMouseOver
CheckBorderBrushCheckedMouseOver
CheckGlyphForegroundCheckedMouseOver
ForegroundCheckedPressed
BackgroundCheckedPressed
BorderBrushCheckedPressed
CheckBackgroundCheckedPressed
CheckBorderBrushCheckedPressed
CheckGlyphForegroundCheckedPressed
ForegroundCheckedDisabled
BackgroundCheckedDisabled
BorderBrushCheckedDisabled
CheckBackgroundCheckedDisabled
CheckBorderBrushCheckedDisabled
CheckGlyphForegroundCheckedDisabled
CheckGlyphIndeterminateTemplate
ForegroundIndeterminate
BackgroundIndeterminate
BorderBrushIndeterminate
CheckBackgroundIndeterminate
CheckBorderBrushIndeterminate
CheckGlyphForegroundIndeterminate
ForegroundIndeterminateMouseOver
BackgroundIndeterminateMouseOver
BorderBrushIndeterminateMouseOver
CheckBackgroundIndeterminateMouseOver
CheckBorderBrushIndeterminateMouseOver
CheckGlyphForegroundIndeterminateMouseOver
ForegroundIndeterminatePressed
BackgroundIndeterminatePressed
BorderBrushIndeterminatePressed
CheckBackgroundIndeterminatePressed
CheckBorderBrushIndeterminatePressed
CheckGlyphForegroundIndeterminatePressed
ForegroundIndeterminateDisabled
BackgroundIndeterminateDisabled
BorderBrushIndeterminateDisabled
CheckBackgroundIndeterminateDisabled
CheckBorderBrushIndeterminateDisabled
CheckGlyphForegroundIndeterminateDisabled

**Comment by timunie** [comment]
Good Morning @punker76,

absolutely impressing how you improved this PR! Many thanks!! :+1:  

Happy coding,
Tim

**Pull request merged**
