### PR TITLE
Add a good "FullScreen : bool" property

### PR DESCRIPTION
**Pull request by GihanSoft**
## Add A FullScreen property with `bool` type (with extra good behaviors).

current way of fullscreen has few problems:
1- when window is max it change to restore state then full screen (I know why it is needed and I put a middle step so it look like no change happend)
2- current fullscreen can be ruined by window menu (Alt + Space). I set a hook lock on window so it can't be changed.

I used it as an attached property maybe the pattern is not that good.

## Additional context

image
the 'move' option is active but actually not works and windows can't be moved.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/MahApps/MahApps.Metro?pullRequest=4055) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/MahApps/MahApps.Metro?pullRequest=4055) before we can accept your contribution.<br/><br/>:x: GihanSoft [sign now](https://cla.dotnetfoundation.org/MahApps/MahApps.Metro?pullRequest=4055)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/MahApps/MahApps.Metro?pullRequest=4055) it.</sub>

**Comment by timunie** [comment]
Hi @GihanSoft 

maybe this PR can be moved to [ControlzEx](https://github.com/ControlzEx/ControlzEx) as the `GlowWindow` is the base for `MetroWindow` and other types of windows, 

/cc @batzen @punker76 

Happy coding 
Tim

**Comment by GihanSoft** [comment]
@timunie so, is it should I send this PR for ControlzEx or you'll do it?

**Comment by batzen** [comment]
@timunie There is no window baseclass in ControlzEx. GlowWindow is just a behavior that can be added to any window 😉

**Comment by timunie** [comment]
@GihanSoft forget what I told you. It was wrong Information. 

@batzen thank you for clarifying it.

**Pull request closed without merging**
