### PR TITLE
Removed margin from ScrollViewer in TextBox style

### LINKED ISSUE #1800: TextBox ScrollBar Top Arrow Misaligned
Hello,

I have just noticed a small cosmetic issue. The top scroll bar arrow in TextBox is slightly shifted to the right and is not aligned with the thumb and the bottom arrow.

textbox

Keep up the good work! 

Thanks.

### PR DESCRIPTION
**Pull request by thoemmi**
Fixes #1800

### CODE REVIEW

**Comment by punker76** [comment]
@thoemmi this change breaks the textbox text margin ui

before
2015-02-16_22h25_48
2015-02-16_22h26_14

after
2015-02-16_22h28_09
2015-02-16_22h28_21

the problem comes from the scrollbar sytles...

2015-02-16_22h43_44

so a better solution should be changing the margins at the `VerticalDecrementTemplate` in the `VerticalScrollBar` style.

```xaml
...

                        <Path Data="F1 M 541.537,173.589L 531.107,173.589L 536.322,167.49L 541.537,173.589 Z "
                              Height="6"
                              Stretch="Uniform"
                              Width="10"
                              Margin="0.5,0,0.5,0"
                              Fill="{DynamicResource GrayBrush1}" />
                        <Path x:Name="HoverPath"
                              Data="F1 M 541.537,173.589L 531.107,173.589L 536.322,167.49L 541.537,173.589 Z "
                              Height="6"
                              Stretch="Uniform"
                              Width="10"
                              UseLayoutRounding="False"
                              Opacity="0"
                              Margin="0.5,0,0.5,0"
                              Fill="{DynamicResource BlackBrush}" />
                        <Path x:Name="Blur"
                              Data="F1 M 541.537,173.589L 531.107,173.589L 536.322,167.49L 541.537,173.589 Z "
                              Height="6"
                              Stretch="Uniform"
                              Width="10"
                              UseLayoutRounding="False"
                              Opacity="0"
                              Margin="0.5,0,0.5,0"
                              Fill="{DynamicResource BlackBrush}">
                            <Path.Effect>
                                <BlurEffect />
                            </Path.Effect>
                        </Path>

...
```

**Comment by thoemmi** [comment]
@punker76 fixed as you suggested. I should have taken a closer look at the original issue :pensive:

**Comment by flagbug** [comment]
@thoemmi Can you rebase this PR? The latest commit conflicts with master

**Comment by thoemmi** [comment]
@punker76 @flagbug Rebase done

**Comment by punker76** [comment]
@thoemmi thx

**Pull request merged**
