### PR TITLE
Auto close flyout [Issue# 1710]

### PR DESCRIPTION
**Pull request by Sikta**
Add IsAutoCloseEnabled and AutoCloseInterval DependencyProperties to the Flyout control using a DispatcherTimer to close the Flyout.

### CODE REVIEW

**Comment by punker76** [comment]
@Sikta thx, merged with some additional changes https://github.com/MahApps/MahApps.Metro/commit/8a77e75e0f095a46dfc8ae90430b7bfbe8311c45

**Comment by Sikta** [comment]
@punker76 thanks for helping me through the pull request process. Glad I could contribute.

**Comment by punker76** [comment]
@Sikta yeah thx for contribution

**Comment by punker76** [comment]
@Sikta yeah thx for contribution

**Comment by punker76** [comment]
@Sikta yeah thx for contribution

**Comment by punker76** [comment]
@Sikta yeah thx for contribution

**Pull request closed without merging**
