### PR TITLE
Fix changing DefaultButtonFocus for MessageDialog

### PR DESCRIPTION
**Pull request by camvinh**
## Describe the changes you have made to improve this project

Fix DefaultButtonFocus error.

The DefaultButtonFocus is always Negative, can't change to the other, except MessageDialogStyle is Affirmative.

### CODE REVIEW

**Comment by punker76** [comment]
@camvinh Thx for contributing to this project! Can you describe the issue for this PR? Thx

**Comment by camvinh** [comment]
> @camvinh Thx for contributing to this project! Can you describe the issue for this PR? Thx

The DefaultButtonFocus always is Negative, cann't change to the other, except MessageDialogStyle is Affirmative

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/MahApps/MahApps.Metro?pullRequest=4247) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/MahApps/MahApps.Metro?pullRequest=4247) before we can accept your contribution.<br/><br/>:x: camvinh [sign now](https://cla.dotnetfoundation.org/MahApps/MahApps.Metro?pullRequest=4247)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/MahApps/MahApps.Metro?pullRequest=4247) it.</sub>

**Comment by punker76** [comment]
@camvinh your changes have been merged, thanks for your contribution 👍

**Pull request merged**
