### PR TITLE
Upgrade WindowPlacementSettings on version change

### LINKED ISSUE #1736: SaveWindowPosition does not upgrade WindowPlacementSettings on version change
When SaveWindowPosition is attached, the WindowPlacementSettings are not "upgraded" when the hosting program's version changes.

I don't see a way for a host to access the WindowPlacementSettings directly because they are protected and marked internal. It would also require a class definition to deserialize the window placement settings for each derived window type (I think). It seems possible the MahApps.Metro Library could upgrade these settings. 

It appears based on my limited understanding that this could be accomplished as follows:

- Add a `UpgradeSettings` property to `IWindowPlacementSettings`, which defaults to `true`
- Add a `void Upgrade()` method to `IWindowPlacementSettings`, which is implemeneted by `ApplicationSettingsBase`
- If on loading the `UpgradeSettings` flag is `true`, call `_settings.Upgrade()`, set the flag to `false`, and then `_settings.Save()`

This is the recommended way user settings are handled by programs.

### PR DESCRIPTION
**Pull request by punker76**
- Added a `UpgradeSettings` property to `IWindowPlacementSettings`, which defaults to true
- Added a `void Upgrade()` method to `IWindowPlacementSettings`, which is implemeneted by `ApplicationSettingsBase`

Closes #1736

### CODE REVIEW

**Comment by punker76** [comment]
@mike-ward is this what you need? is this enough?

**Comment by mike-ward** [comment]
I think the `Upgrade` method is all that is really needed. It's typical for apps to have their own `UpgradeSettings` property.

**Comment by punker76** [comment]
@mike-ward so the others (at th einterface) too much?

**Comment by mike-ward** [comment]
Probably. I can't think of a use case where I would want to reset or reload those settings. For my use case, 'Upgrade` is sufficent.

**Comment by punker76** [comment]
@mike-ward ok, you're right. i removed the reset method, but leave the save method, i think that's also recommended.

**Comment by flagbug** [comment]
Hm, that's a breaking change, but I guess it's alright

**Comment by mike-ward** [comment]
Upgraded to 1.1.0. Could I get a quick tutorial on how to upgrade settings? Here is what I've tried.

In App.xaml.cs, `OnStartup()`

    var windowPlacementSettings = mainWindow.GetWindowPlacementSettings();

    if (windowPlacementSettings.UpgradeSettings)
    {
        windowPlacementSettings.Upgrade();
        windowPlacementSettings.UpgradeSettings = false;
        windowPlacementSettings.Save();
    }

UpgradeSettings is always false. I must be missing something else where?

**Comment by punker76** [comment]
it's a mistake with `DefaultValue(true)` and auto property, i'll fix this
tomorrow and publish a 1.1.1 version
Am 25.02.2015 00:56 schrieb "Mike Ward" <notifications@github.com>:

**Comment by mike-ward** [comment]
Cool beans! The window snap restore thing is working nicely.

**Comment by punker76** [comment]
@mike-ward `UpgradeSettings` should now work :-D 509bd7743e0e31fc3f63cd419432d633869ad743

**Comment by mike-ward** [comment]
Different problem. Using code from above, `UpgradeSettings` is always `true` now.

**Comment by punker76** [comment]
@mike-ward to clarify this, i will change the implementation to this

`` csharp
        /// <summary>
        /// Upgrades the application settings on loading.
        /// </summary>
        [UserScopedSetting]
        public bool UpgradeSettings
        {
            get
            {
                if (this["UpgradeSettings"] != null)
                {
                    return (bool)this["UpgradeSettings"];
                }
                return true;
            }
            set { this["UpgradeSettings"] = value; }
        }
```

with the result

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <configSections>
        <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
            <section name="MahApps.Metro.Controls.WindowApplicationSettings.MetroDemo.ExampleWindows.FlyoutDemo" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
        </sectionGroup>
    </configSections>
    <userSettings>
        <MahApps.Metro.Controls.WindowApplicationSettings.MetroDemo.ExampleWindows.FlyoutDemo>
            <setting name="UpgradeSettings" serializeAs="String">
                <value>False</value>
            </setting>
            <setting name="Placement" serializeAs="Xml">
                <value>
                    <WINDOWPLACEMENT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                        <length>44</length>
                        <flags>0</flags>
                        <showCmd>1</showCmd>
                        <minPosition>
                            <X>-1</X>
                            <Y>-1</Y>
                        </minPosition>
                        <maxPosition>
                            <X>-1</X>
                            <Y>-1</Y>
                        </maxPosition>
                        <normalPosition>
                            <left>1028</left>
                            <top>418</top>
                            <right>1903</right>
                            <bottom>1043</bottom>
                        </normalPosition>
                    </WINDOWPLACEMENT>
                </value>
            </setting>
        </MahApps.Metro.Controls.WindowApplicationSettings.MetroDemo.ExampleWindows.FlyoutDemo>
    </userSettings>
</configuration>
```

is this what you want?

**Comment by mike-ward** [comment]
Yep, I think that will work. Thanks for doing this.

**Comment by punker76** [comment]
@mike-ward np, but can you give me a reason why a user want change this property in this file? i don't see the benefit, maybe i'm blind ;-)

**Comment by mike-ward** [comment]
You only want to upgrade the settings once per version bump. The suggested
way to do this is:

http://blog.johnsworkshop.net/automatically-upgrading-user-settings-after-an-application-version-change/

It doesn't matter to me if I keep a flag in my user settings or use the
MahApp supplied flag. If you decide not to persist the flag then I would
suggest removing it.

**Pull request merged**
