### PR TITLE
[WIP] Changed the behaviour and design ot ToggleSwitch

### PR DESCRIPTION
**Pull request by timunie**
This is just the first try and not ready for use. But as my implementation will lead to a breaking change i would like to have a first feedback, if we should go this way or not.

**Describe the changes you have made to improve this project**

* Added a Style for the intermediate state
* Changed the behavior how the switch will change the state
* Added a intermediate label property
* changed the labels from string to object to provide more options for the labels (color, symbol, etc.)

That we need to do before we release this
* [x] Decide, if we need a ToggleSwitch and ToggleSwitchButton (Maybe there is a reason that i don't understand, I am not a programmer by profession, sorry for my question here) 
* [x] Fix some issues with the click event
* [x] Provide more Brushes to the user to control the apperance of the different states
* [x] Make a new DP that indicates if the Intermediate state is allowed or not. (Maybe we can also check if the binded property is 'bool?' or 'bool'

**Unit test**

If it's possible then make a unit test for your changes.

**Additional context**

image

**Closed Issues**
#3276

### CODE REVIEW

**Comment by timunie** [comment]
@punker76 May I ask you to give me a :+1: or :-1: (No need for code review or a long comment yet), just to indicate if you want me to work on this or not? Many thanks in advance.

**Comment by punker76** [comment]
@timunie The `ToggleSwitch` uses the `ToggleSwitchButton` and can show a header and content. So the `ToggleSwitchButton` is really only the toggle button.

**Comment by timunie** [comment]
@punker76 Thanks for clarification. Then we cannot drop one of tem to avoid some code twice.

**Comment by timunie** [comment]
Hello @punker76 ,

in my opinion this PR is ready for review. So if you have some free time, I kindly ask you to have a look at my code. :smiley: 


Happy coding 

Tim

**Comment by timunie** [comment]
Hi @punker76 

Should I try fix the conflicts? 

Conflicting files
src/MahApps.Metro/Styles/Controls.ToggleSwitch.xaml
src/MahApps.Metro/Themes/ToggleSwitch.xaml

Happy coding
Tim

**Comment by DoubleOhmSeven** [comment]
@timunie @punker76 Looking forward to this PR, I think it would be a welcome addition. Many other ToggleSwitches support it, such as https://documentation.devexpress.com/WPF/117154/Controls-and-Libraries/Data-Editors/Editor-Types/ToggleSwitch.

The feedback I have for this PR: everything intermediate should be called indeterminate. To keep existing stuff compatible it might be useful to revert the string > object changes.

**Comment by timunie** [comment]
Hi @punker76 ,
as discussed yesterday I solved the conflicts now. Unfortunatally the style is a bit broken with this change. I think it is not much work to get this done, but I want to wait until you took a look if you are happy with the new implementation or not (No need to hurry :tornado: ). 

Happy coding
Tim

**Pull request closed without merging**
