### PR TITLE
Enable nullable and set TreatWarningsAsErrors to true

### LINKED ISSUE #4036: Time Picker Hours starts with 12
## Describe the bug

The hours combox box of the Time Picker U.I starts with 12. 
My regional format is English (Germany).

## Steps to reproduce

Use the Mahapps.Demo. see screenshot.
image

## Expected behavior
The hours combox box of the Time Picker is numerically sorted from 1 - 12 with 12 at the bottom.

## Environment

```
MahApps.Metro version: v2.4.3
Target Framework: .NET framework .v4.7.2

```

### LINKED ISSUE #4048: EnableCellEditAssist should handle the message dispatched from the popup control
## Describe the bug

I have a popup control that is opened from the column header, when the popup opened, it will cover the first cell (a checkbox cell), when the user clicks the popup and `EnableCellEditAssist ` is true, the checkbox cell will change the check state value.

## Environment

```
MahApps.Metro version: v2.3.0
Windows build number: Win10 1909 [Version 10.0.18363.836]
Visual Studio: 2019 16.6.0
Target Framework: .Net Core 3.1 (v4.5.2, v4.7.2)
```

## Screenshots

Screenshot 1, the popup not opened:

image

Screenshot 2, the popup opened by clicking the filter icon:

image

When the user click the space between 2 `Checkbox`s in screenshot2, the first check box cell in the `DataGrid` (I mean the checkbox cell in screenshot1) will be checked.

### PR DESCRIPTION
**Pull request by batzen**
This PR enables nullable everywhere, except in the test project, and sets TreatWarningsAsErrors to true for all projects.

We can enable it there also if xUnit supports nullable annotations.

A few places need further review as i changed a few property types.

## Additional Changes

- Remove unused internal TimeSpanToStringConverter
- Remove MetroTabItemCloseButtonWidthConverter and use MathMultiplyConverter instead
- Adding Box overload for nullable bool
- (#4048) Simplified One-Click edit of elements like comboboxes and checkboxes in datagrids
- (#4036) Allow TimePicker to set a comparer for Am/Pm values
- Remove BindableResourceBehavior
- Change RevealImage from UserControl to Control (new Style MahApps.Styles.RevealImage)
- Add new template for PivotItem (MahApps.Templates.PivotItemHeader)
- New Header property for PivotItem
- Move GetCaption from WindowButtonCommands to WinApiHelper

## Closes Issues

Closes #4048 
Closes #4036

### CODE REVIEW

**Comment by batzen** [comment]
@timunie could you review the changes i made to the color picker?

**Comment by batzen** [comment]
@punker76 The changes in src/MahApps.Metro/MahAppsException.cs might be interesting for you.

**Comment by timunie** [comment]
Hi @batzen 

unfortunatally your changes breaks the `ColorPicker`. Changing `Dictionary<Color?, string>` to `Dictionary<Color, string>` gives wrong default value `#000000` instead of `null`

Happy coding 
Tim

**Comment by batzen** [comment]
Ah, that's what it was used for.
Will change it back to a nullable color then.

**Comment by batzen** [comment]
@timunie Ah, now i know why i changed it from Color? to Color.
The generic key parameter for Dictionary has a not null constraint on it, thus disallowing null values to be used.
Even though this works without nullable enabled, it might change at some point in time.

How can i reproduce the issue you described?

**Comment by timunie** [comment]
Maybe there is an even better option for it, as normally `null` is not a valid `key` but I had no better idea so far. If you have, feel free to teach me.

**Comment by timunie** [comment]
@batzen should we discuss this issue on gitter maybe?

**Review by timunie — APPROVED** [review]

**Review by punker76 — APPROVED** [review]
👍🏻 LGTM

**Comment by punker76** [comment]
@batzen your changes have been merged, thanks for your contribution 👍

**Pull request merged**
