### PR TITLE
Change solution project build order.

### PR DESCRIPTION
**Pull request by scccboom**
Include xaml in the project.

### CODE REVIEW

**Comment by punker76** [comment]
@scccboom What was your issue? Or what is the benefit for this change?

**Comment by MurariAlex** [comment]
@punker76 I may be missing something, but the demo project doesn´t have the ".xaml" files referenced in it. Only the code behind files ".xaml.cs" files appear in the solution explorer, making it harder to open the designer in VS. Is it intentional? If it´s not, I think this PR will help.

**Comment by punker76** [comment]
@MurariAlex It's all there 😕 

image

**Comment by MurariAlex** [comment]
@punker76 Strangely it´s not working for me. I just downloaded the latest src to test it, through the "clone or download" button.
I didn´t change anything, just downloaded and opened.

image

**Comment by punker76** [comment]
@MurariAlex Just tested this on VS 2017 15.4.0 and VS 2015 14.0.25431.01 and I can see no difference... it's all there. So what is your VS version?

**Comment by MurariAlex** [comment]
@punker76  Visual Studio 2015 14.0.25431.01 Update 3. Trying to figure out if an extension could be the resposible for this, but for now I have no clue.

**Comment by MurariAlex** [comment]
@punker76 Adding the xaml files through "Add -> Existing Item" solves the problem, but obviously the "MahApps.Metro.Demo.Shared.projitems" file is modified:

Adding the `ButtonsExample.xaml` and `ColorsExample.xaml` files result in an new nod an new items:

``` xml
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)ExampleViews\ButtonsExample.xaml" />
    <None Include="$(MSBuildThisFileDirectory)ExampleViews\ColorExample.xaml" />
  </ItemGroup>
```

This is basically what this PR does, so in not the only one facing this issue... now I really wanna now why your VS correctly displays the items.  😕

**Comment by thoemmi** [comment]
I experience the same issue, no .xaml files in the sample applications.

**Comment by punker76** [comment]
@MurariAlex @thoemmi Normally if the Compile tag in a csproj file contains the DependentUpon the `.xaml.cs` and `.xaml` (or any other file) should be shown as grouped.

```
<Compile Include="$(MSBuildThisFileDirectory)ExampleViews\ButtonsExample.xaml.cs">
  <DependentUpon>ButtonsExample.xaml</DependentUpon>
</Compile>

<Page Include="$(MSBuildThisFileDirectory)ExampleViews\ButtonsExample.xaml">
  <SubType>Designer</SubType>
  <Generator>MSBuild:Compile</Generator>
</Page>
```

I forced this on this branch, so please test it on your machines

https://github.com/MahApps/MahApps.Metro/tree/feature/SharedProject_Xaml_DependentUpon

thy

**Comment by punker76** [comment]
@MurariAlex @thoemmi damn `<Compile Update="**\*.xaml.cs" SubType="Code" DependentUpon="%(Filename)" />` doesn't work in VS 2015.

**Comment by punker76** [comment]
@MurariAlex @thoemmi I've never had any trouble with it. Maybe it helps you delete the `. vs`, `. suo` files and the `bin` and `obj` folders?

**Comment by punker76** [comment]
by the way, if I load this PR in VS the demo project doesn't load anymore...

**Comment by MurariAlex** [comment]
@punker76 Yeah, `Compile` tag is invalid, the project doesn´t even load. This PR introduces this tag... it breaks VS2015 compatibility.

But adding this to the `MahApps.Metro.Demo.Shared.projitems` solves for me and doesn´t break anything (I think).

```
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)App.xaml" />
    <None Include="$(MSBuildThisFileDirectory)ExampleViews\ButtonsExample.xaml" />
    <None Include="$(MSBuildThisFileDirectory)ExampleViews\ColorExample.xaml" />
    <None Include="$(MSBuildThisFileDirectory)ExampleViews\CustomDialogExample.xaml" />
    <None Include="$(MSBuildThisFileDirectory)ExampleViews\DataGridExamples.xaml" />
    <None Include="$(MSBuildThisFileDirectory)ExampleViews\DateExamples.xaml" />
    <None Include="$(MSBuildThisFileDirectory)ExampleViews\HamburgerMenuSample.xaml" />
    <None Include="$(MSBuildThisFileDirectory)ExampleViews\OtherExamples.xaml" />
    <None Include="$(MSBuildThisFileDirectory)ExampleViews\SelectionExamples.xaml" />
    <None Include="$(MSBuildThisFileDirectory)ExampleViews\SliderProgressExamples.xaml" />
    <None Include="$(MSBuildThisFileDirectory)ExampleViews\SplitViewExamples.xaml" />
    <None Include="$(MSBuildThisFileDirectory)ExampleViews\TabControlExamples.xaml" />
    <None Include="$(MSBuildThisFileDirectory)ExampleViews\TextExamples.xaml" />
    <None Include="$(MSBuildThisFileDirectory)ExampleViews\TilesExample.xaml" />
    <None Include="$(MSBuildThisFileDirectory)ExampleWindows\CleanWindowDemo.xaml" />
    <None Include="$(MSBuildThisFileDirectory)ExampleWindows\DynamicFlyout.xaml" />
    <None Include="$(MSBuildThisFileDirectory)ExampleWindows\FlyoutDemo.xaml" />
    <None Include="$(MSBuildThisFileDirectory)ExampleWindows\InteropDemo.xaml" />
    <None Include="$(MSBuildThisFileDirectory)ExampleWindows\ShowcaseFlyout.xaml" />
    <None Include="$(MSBuildThisFileDirectory)ExampleWindows\SizeToContentDemo.xaml" />
    <None Include="$(MSBuildThisFileDirectory)ExampleWindows\VSDemo.xaml" />
    <None Include="$(MSBuildThisFileDirectory)MainWindow.xaml" />
    <None Include="$(MSBuildThisFileDirectory)Navigation\HomePage.xaml" />
    <None Include="$(MSBuildThisFileDirectory)Navigation\InterestingPage.xaml" />
  </ItemGroup>
```

**Comment by punker76** [comment]
@MurariAlex it's not working for me...

image

**Comment by MurariAlex** [comment]
@punker76 VS 2017?

**Comment by punker76** [comment]
@MurariAlex VS 2015

**Comment by MurariAlex** [comment]
@punker76 Same as mine, VS 2015 Pro. That´s weird... gonna dig deeper, find out what´s going on.

gif

**Comment by punker76** [comment]
@MurariAlex maybe I found the problem and when I read it, I couldn't believe it. It seems it' necessary to install the `Windows 8.1 SDK` :-(

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/26291339-e8fd-4596-980a-7befa63a1f7c/missing-folders-files-add-item-options-in-shared-project?forum=visualstudiogeneral

https://www.cool-it.at/blog/Oktober-2016/Visual-Studio-2015-Fehlende-Code-Behind-Verknupfun

**Comment by punker76** [comment]
@MurariAlex ...

image

**Comment by MurariAlex** [comment]
@punker76 That´s definitely weird... hate messing with VS installation... but i'm gonna give it a try. Thy.

**Comment by punker76** [comment]
@MurariAlex Have you tried it out?

**Comment by MurariAlex** [comment]
@punker76 Not yet, busy week, couldn't modify the VS installation. Gonna try it tomorrow, today I have a Mike Portnoy concert to go. \,,/

**Comment by punker76** [comment]
@MurariAlex np, have fun!

**Comment by MurariAlex** [comment]
@punker76 Tried it, it worked. So that's was it... downside is that it adds 7GB of data to the VS installation.

**Comment by punker76** [comment]
@MurariAlex I know that's confusing. I didn't know that this must be installed to get full support for shared projects...

**Comment by thoemmi** [comment]
I can confirm that after installing the Windows 8.1 SDK, XAML files finally appeared in Visual Studio 2017.

image

Nevertheless it's not straight-forward. Thanks for the hint, @punker76 :+1:

**Pull request closed without merging**
