### PR TITLE
Adds an implementation of the SplitView control.

### PR DESCRIPTION
**Pull request by Evangelink**
Adds a SplitView control to MahApps. This control is based upon the SplitView control from [my fork of the UniversalWPF](https://github.com/Evangelink/UniversalWPF) project.

I have added 2 examples, the first one which simply demonstrates the functionnalities of the control. The second one is a simple styled example that would require some more work to get something nice and easy to use. Also I am not sure of how the style should come with as there are many ways to put icons.

Feel free to ping me if you think the control needs more work before being merged with MahApps.

### CODE REVIEW

**Comment by punker76** [comment]
@Evangelink Thx. Maybe you can add my fixes too? -> https://github.com/dotMorten/UniversalWPF/pull/14

**Comment by Evangelink** [comment]
@punker76 Sorry I didn't paid attention to the original repo as there is no activity :(

I have just tried to replace the default style by the one you provided on your commit and the split view has stopped working properly. Did you had any issues with the commit you did ?

**Comment by punker76** [comment]
@Evangelink Yes, all described here https://github.com/dotMorten/UniversalWPF/pull/14
You can look to the commits for what I changed https://github.com/dotMorten/UniversalWPF/pull/14/commits

**Comment by Evangelink** [comment]
@punker76 I have just realised your fixes where on the original SplitView commit not on my last update (which hasn't been merged yet...). Should I revert my changes to take your fixes or do we continue with my code ? I had to make some hack to get the control to fully/properly work.

**Comment by punker76** [comment]
@Evangelink I don't know. I'll take a look later to your changes. But hacks doesn't sounds good... and with your code reformating it is also hard to see what you really changed.

**Comment by Evangelink** [comment]
@punker76 Here you go. 

And thanks for the example of the FrameworkElement as proxy it is gonna make my future code cleaner!

**Comment by Evangelink** [comment]
@punker76 I have made a mistake. I have added some code that was supposed to go to a new PR but everything has end up here. Any idea on how I fix this? Sorry...

**Comment by punker76** [comment]
@Evangelink You can revert your last change and commit it here.

**Pull request closed without merging**
