### PR TITLE
Changing blue color scheme to blue

### PR DESCRIPTION
**Pull request by batzen**
This PR changes to blue color scheme to a "real" blue.
@punker76 we already chatted about this ;-)

### CODE REVIEW

**Comment by timunie** [comment]
Hi @batzen ,
I liked the old blue value. I'm with you that blue should be blue but may we keep the old `Theme` under a new Name? What do you think? 

P. S. : If I'm the only one I don't mind this change because I generate my `Themes` at runtime. I just thought others might want to keep their Theme as well. 

Happy coding 
Tim

**Comment by batzen** [comment]
Adding new color variants is very easy.
But the current/old blue is in fact cyan.
image
Left: current/old blue
Right: cyan

**Comment by timunie** [comment]
@batzen thank you this ia a really good point. :+1:

**Comment by punker76** [comment]
@batzen your changes have been merged, thanks for your contribution 👍

**Pull request merged**
