### PR TITLE
Fix ideal foreground for some color styles

### PR DESCRIPTION
**Pull request by Alkalinee**
Here, look at this:
Preview
For the most styles, it looks better with a white title (in my opinion)

### CODE REVIEW

**Comment by flagbug** [comment]
Seems like there's an unrelated change to the input dialog in this PR

**Comment by Alkalinee** [comment]
Sorry, i've removed that.

**Comment by punker76** [comment]
thx @Alkalinee

**Comment by flagbug** [comment]
Hm, this is a "breaking change", at least visually, how should we handle this?

**Comment by robertstefan** [comment]
This seems to be happening for a short period of time. The last time I used MA.M [August - September '14] with one of the above accents [Cyan], the text was white. :-/

**Pull request merged**
