### PR TITLE
Watermark Enhancements

### PR DESCRIPTION
**Pull request by amkuchta**
## Proposed Changes
This re-introduces the watermark enhancements proposed in #2898 - I have recreated them, this time with proper code formatting up-front so that the review process is easier for @thoemmi & @punker76 .  

#### Progress:
- [x] **_Watermark TextTrimming:_** Fully implemented across TextBox, PasswordBox, ComboBox, DatePicker, DateTimePicker, NumericUpDown
- [x] **_Watermark TextWrapping:_** Implemented on TextBox controls to follow the templated TextWrapping selection - I can't see any reason to implement this on the other controls, as they typically don't wrap 
- [x] **_FloatingWatermarkOverrideText:_** Fully implemented across TextBox, PasswordBox, ComboBox, DatePicker, DateTimePicker, NumericUpDown
- [x] **_FloatingWatermarkLocation:_** Fully implemented across TextBox, PasswordBox, ComboBox, DatePicker, DateTimePicker, NumericUpDown

I've also added a "Watermark Enhancements" section in `TextView` to make reviewing functionality across all controls easier - I can delete this once the review is complete, before the merge, if desired.  Finally, it's worth noting that all original default settings are maintained - `FloatingWatermarkLocation` defaults to "Interior", `WatermarkTextTrimming` defaults to "Word", and `FloatingWatermarkOverrideText` only triggers if `FloatingWatermarkOverrideText.Length > 0`

## Closed issues
#2884 
#2889

### CODE REVIEW

**Comment by amkuchta** [comment]
Revert completed

**Comment by amkuchta** [comment]
@punker76 I got the two floating watermarks that weren't getting focus colors applied correctly (NumericUpDown and ComboBox when `IsEditable="True"`).  This completely finalizes implementation of the enhancements and makes the PR ready for merging.

**Comment by punker76** [comment]
@amkuchta Long waiting... but now I just implemented your idea of TextTrimming and TextWrapping. 👍 

But I will not implement the 2 other things FloatingWatermarkOverrideText and FloatingWatermarkLocation.

I have thought about it for a long time and come to the conclusion that this does not fit here. I think the first property can be solved from outside with triggers who listen to the HasText property.

The FloatingWatermarkLocation is too specific and is not a common ui design (I've never seen this before).

Nevertheless, thanks for your ideas and effort.

/cc @thoemmi

**Comment by amkuchta** [comment]
@punker76 I understand.  I will define my own style based on yours and give using `HasText` as a trigger a shot.

As for the other two items that were utilized, glad to help!

**Comment by amkuchta** [comment]
@punker76 @thoemmi I know it isn't going to be incorporated, but I thought it would be nice to share the finalized `FloatingWatermark` change I made (for closure :laughing:).  I ended up setting the control up in such a way that the layout of the window never changes when the `FloatingWatermark` appears, which is cleaner (thx for the idea, @thoemmi).  I also see this as more of a `Header` than a `FloatingWatermark`, so I've aptly named the style `HeaderedTextBoxStyle`. Finally, I created a `DependencyProperty` for the `FloatingWatermarkText ` that defaults back to the `Watermark` if it is not specifically set, and a `FloatingWatermarkForeground` that can be set if need be (e.g. when using the control in a `DataGrid`, where the standard brush looks out of place). Now to roll them for the other controls! Screenshot below (animations are much smoother in person, frame rate isn't high enough on the gif):

headeredtextbox

**Pull request closed without merging**
