### PR TITLE
[WIP] MessageDialogIcons

### LINKED ISSUE #1474: Background Icon for Dialogs
Now, don't get me wrong, I don't think WinForms is generally a great model for what we should do from a UI perspective, but I was hoping to add some mechanism to differentiate different Dialogs as I present them to a user (e.g. Error, Warning, Info, etc.).

`MessageBox.Show` has the `MessageBoxIcon` property.

Perhaps adding a new DP on BaseMetroDialog that pointed to some `Visual` data for an icon. So, we could create a dialog with background icons from [Modern UI Icons](http://www.modernuiicons.com) that inform the user on what kind of error is happening:

error_message2

Something like the above, but maybe overlaying the text (hard to do in paint) and more transparent, as to be much more subtle.

At the very least, it'd be nice to differentiate, stylistically, between error, warning, and info dialogs.

### PR DESCRIPTION
**Pull request by michaelmairegger**
resolves #1474 
- [x] Testing on LimitedSizeDialog
- [x] Testing on LoginDialog
- [x] Testing on ProgressDialog
- [x] Testing on CustomDialog **icon is passed to the control, but as it is custom, the developer must place the icon in XAML by himself**
- [x] Testing on InputDialog
- [x] Testing with IDialogCoordinator
- [x] ~~Discussion about refactoring (**see my comment below**)~~
- [x] Theme: Dark, UseAccent=false 
  darknoaccent
- [x] Theme: Light, UseAccent=false
  lightnoaccent
- [x] Theme: Dark, UseAccent=true(light is slightly the same)
  darkaccent

### CODE REVIEW

**Comment by xxMUROxx** [comment]
I would refactor the following methods because I think `icon` is more frequently set than `settings` *But the change is a braking change*

1. 
 - **FROM** > *public static Task<LoginDialogData> ShowLoginAsync(this MetroWindow, string title, string message, LoginDialogSettings settings = null,* **object icon = null**)
 - **TO** > *public static Task<LoginDialogData> ShowLoginAsync(this MetroWindow, string title, string message*, **object icon = null***, LoginDialogSettings settings = null)*
2. 
 - **FROM** > *public static Task<string> ShowInputAsync(this MetroWindow window, string title, string message, MetroDialogSettings settings = null,* **object icon = null**)
 - **TO** > *public static Task<string> ShowInputAsync(this MetroWindow window, string title, string message*, **object icon = null** *, MetroDialogSettings settings = null)*
3. 
 - **FROM** > *public static Task<MessageDialogResult> ShowMessageAsync(this MetroWindow window, string title, string message, MessageDialogStyle style = MessageDialogStyle.Affirmative, MetroDialogSettings settings = null,* **object icon = null**)
 - **TO** > *public static Task<MessageDialogResult> ShowMessageAsync(this MetroWindow window, string title, string message, MessageDialogStyle style = MessageDialogStyle.Affirmative,* **object icon = null** *, MetroDialogSettings settings = null)*
4. 
 - **FROM** > *public static Task<ProgressDialogController> ShowProgressAsync(this MetroWindow window, string title, string message, bool isCancelable = false, MetroDialogSettings settings = null,* **object icon = null**)
 - **TO** > *public static Task<ProgressDialogController> ShowProgressAsync(this MetroWindow window, string title, string message, bool isCancelable = false,* **object icon = null** *, MetroDialogSettings settings = null)*

**Comment by thoemmi** [comment]
Your mileage may var. I'd keep the order of parameters as is. Users still can use named parameters: `window.ShowLoginAsync("my title", "my message", icon: myIcon)`.

**Comment by xxMUROxx** [comment]
@punker76 Saw that this PR is on `master` since it is a old one

**Comment by xxMUROxx** [comment]
@punker76 I think this is completed too.

**Comment by thoemmi** [comment]
BTW, there lots of empty lines at the end of [`MainWindow.xaml`](https://github.com/xxMUROxx/MahApps.Metro/blob/76b8629ab0c1339dd7f670777841077304399dea/samples/MetroDemo/MainWindow.xaml#L269-L331)

**Comment by Malavos** [comment]
That is looking really good! Great work!

Could we add it to the documentation, with an example?

**Comment by xxMUROxx** [comment]
@Malavos Done. I will create a PR on the documentation when this PR is merged.
@punker76 we have to merge this changes manually to `develop` because closing this PR would merge on `master`.

**Comment by punker76** [comment]
@xxMUROxx I know ;-)

**Comment by Malavos** [comment]
@xxMUROxx  thank you very much.

I'm helping some friends with WPF, and we are using MahApps. The docs help them a lot, specially with examples.

**Comment by xxMUROxx** [comment]
@punker76 Now develop is integrated in this branch and is fully compiling.

**Comment by xxMUROxx** [comment]
@punker76 what is the plan for this PR? Do you intend to merge it or is the plan to left the feature out of MahApps?

**Comment by punker76** [comment]
@xxMUROxx Yes, but I have some suggestions...

- Instead passing the icon through parameter on each method, why not adding 2 new properties to the MetroDialogSettings?
```
public object Icon { get; set; }
public DataTemplate IconTemplate { get; set; }
```
- We can set the default `ItemTemplateSelector` at the ctor of the MetroDialogSettings (via dynamic resource).
- The ContentPresenter  then can also use TemplateBinding to the IconTemplateSelector.
```
<ContentPresenter
  Grid.Row="0"
  Grid.Column="0"
  Margin="0 0 20 0"
  HorizontalAlignment="Right"
  VerticalAlignment="Center"
  Content="{TemplateBinding Icon}"
  ContentTemplate="{TemplateBinding IconTemplate}"
  ContentTemplateSelector="{TemplateBinding IconTemplateSelector}" />
```

I think this makes it possible to change the DataTemplate for the icon and a use can do anything.

**Comment by timunie** [comment]
One more idea to this PR:

At the moment the Control is defined in XAML like an `UserControl`. Most other `Controls` are defined in a `Style` with `ControlTemplate`. This makes it possible to change the whole `ControlTemplate` if one wants to do. With the current implementation this is not so easy. 

I would jump in here if you want me to.

Happy coding
Tim

**Pull request closed without merging**
