### PR TITLE
[WIP] Auto close flyout [Issue# 1710]

### PR DESCRIPTION
**Pull request by Sikta**
Add IsAutoCloseEnabled and AutoCloseInterval DependencyProperties to the Flyout control using a DispatcherTimer to close the Flyout.

### CODE REVIEW

**Comment by Sikta** [comment]
I added a demo to the Flyout demo. I need to add some tests but have to figure out the testing framework that is being used (xunit?). 

I'm also thinking of adding another DependencyProperty that would allow the AutoClose timer to not run if the mouse is over the Flyout to give it behavior kind of like a ToolTip.

**Comment by Sikta** [comment]
I think I messed up this pull request as it looks like it has other code changes than my own. I thought I followed the steps in the contributing guide correctly but I'll probably have to try this again.

**Comment by Sikta** [comment]
I guess I'm not really sure if this pull request is valid. The "Files changed" tab shows only my changes but the "Commits" tab shows a 2nd commit with changes that aren't my own. Can someone take a glance at this and tell me if I need to do something differently?

**Comment by punker76** [comment]
@Sikta cause your changes are on the master and the other change is from original master merged in your changes to this pr. so it's always better to create branches before making changes and prs.

**Comment by Sikta** [comment]
If I understand you correctly, you are saying I should've issued this pull request to MahApps.Metro's master branch from my forked feature branch rather than my master branch?

**Comment by punker76** [comment]
yes

**Comment by Sikta** [comment]
Thanks, I created a new pull request and it looks correct now.

**Pull request closed without merging**
