### PR TITLE
Add new CharacterCasing keys

### LINKED ISSUE #4126: Provide easy way to globally DISABLE FORCED ALL CAPS
It would be **super** convenient to easily disable the forced all caps **globally** for MahApps.Metro. 

I know about the TitleCharacterCasing property of the MetroWindow class, but it seems to only affect that one control. I've also seen a few examples of ways of doing this on other controls, but as far as I can tell, you have to do a fairly involved "restyling" of each control individually to make this happen - it's a lot of XAML code just to turn this one thing off and avoid having your app yell at your users.

If this already exists, apologies in advance. I swear, I really did look pretty extensively and didn't find it!

### PR DESCRIPTION
**Pull request by punker76**
## Describe the changes you have made to improve this project

Add new CharacterCasing keys:

- MahApps.CharacterCasing.Button
- MahApps.CharacterCasing.Button.Square
- MahApps.CharacterCasing.Button.Dialogs
- MahApps.CharacterCasing.Button.Dialogs.Accent
- MahApps.CharacterCasing.Button.Dialogs.AccentHighlight
- MahApps.CharacterCasing.DataGridColumnHeader
- MahApps.CharacterCasing.Expander
- MahApps.CharacterCasing.Expander.VisualStudio
- MahApps.CharacterCasing.GroupBox
- MahApps.CharacterCasing.GroupBox.VisualStudio
- MahApps.CharacterCasing.GridViewColumnHeader
- MahApps.CharacterCasing.ColorEyeDropper
- MahApps.CharacterCasing.ColorPalette
- MahApps.CharacterCasing.HotKeyBox
- MahApps.CharacterCasing.WindowCommands
- MahApps.CharacterCasing.WindowCommands.Clean

## Closed Issues

Closes #4126

### CODE REVIEW

**Comment by FroggieFrog** [comment]
What will be the typical use to disable the forced upper case (docs?)?
Issue #4126 was specifically to make it easier and NOT define settings for every possible control.

**Comment by punker76** [comment]
@FroggieFrog You can now override these casing in your App.xaml


```xaml
<CharacterCasing x:Key="MahApps.CharacterCasing.Button">Normal</CharacterCasing>
<CharacterCasing x:Key="MahApps.CharacterCasing.Button.Square">Normal</CharacterCasing>
<CharacterCasing x:Key="MahApps.CharacterCasing.Button.Dialogs">Normal</CharacterCasing>
<CharacterCasing x:Key="MahApps.CharacterCasing.Button.Dialogs.Accent">Normal</CharacterCasing>
<CharacterCasing x:Key="MahApps.CharacterCasing.Button.Dialogs.AccentHighlight">Normal</CharacterCasing>
<CharacterCasing x:Key="MahApps.CharacterCasing.DataGridColumnHeader">Normal</CharacterCasing>
<CharacterCasing x:Key="MahApps.CharacterCasing.Expander">Normal</CharacterCasing>
<CharacterCasing x:Key="MahApps.CharacterCasing.Expander.VisualStudio">Normal</CharacterCasing>
<CharacterCasing x:Key="MahApps.CharacterCasing.GroupBox">Normal</CharacterCasing>
<CharacterCasing x:Key="MahApps.CharacterCasing.GroupBox.VisualStudio">Normal</CharacterCasing>
<CharacterCasing x:Key="MahApps.CharacterCasing.GridViewColumnHeader">Normal</CharacterCasing>
<CharacterCasing x:Key="MahApps.CharacterCasing.ColorEyeDropper">Normal</CharacterCasing>
<CharacterCasing x:Key="MahApps.CharacterCasing.ColorPalette">Normal</CharacterCasing>
<CharacterCasing x:Key="MahApps.CharacterCasing.HotKeyBox">Normal</CharacterCasing>
<CharacterCasing x:Key="MahApps.CharacterCasing.WindowCommands">Normal</CharacterCasing>
<CharacterCasing x:Key="MahApps.CharacterCasing.WindowCommands.Clean">Normal</CharacterCasing>
```

**Comment by punker76** [comment]
@FroggieFrog No need to override any style anymore.

**Comment by FroggieFrog** [comment]
It is an improvement (thanks for that), but has to be done several times.
Is it possible to provide a one-liner to the user?

**Comment by timunie** [comment]
@FroggieFrog  tbh I don't see a oneliner here. I think this is the way WPF and XAML works. But I know that you sometimes have good ideas, so if you see a oneliner feel free to share with us. 

P.S.: Maybe one can do a three-liner if one iterates over all Resources in code behind and change it for each `CharacterCasing`-Key. I didn't test it yet. 

Happy coding
Tim

**Pull request merged**
