### PR TITLE
create new class of Thumb in order to be better in Touch environment

### PR DESCRIPTION
**Pull request by ycaoyang**
In touch environment, touching a slider won't make its thumb following user's finger, for another visual has capture the touch-device. In order to make the Thumb touchable, we have to capture the touch-device in himself. So here it is.

PS : correct branch selection

### CODE REVIEW

**Comment by Amrykid** [comment]
@ycaoyang Make sure to add your thumb class to the same directory in the MahApps.Metro.NET45 solution as well.

**Comment by punker76** [comment]
@All can someone test this? I don't have a touch device...

**Comment by Kalashn** [comment]
is this fix present in one of the current alpha releases available on nuget? if so, i'll test it with pleasure (on only one touch device though)

**Comment by punker76** [comment]
@Kalashn you can clone this pr `https://github.com/ycaoyang/MahApps.Metro/tree/y.cao`

**Comment by Kalashn** [comment]
Thanks, I quite new to github. I'll run the tests this weekend. Any procedures or tools I have to use? Otherwise it will be just a basic: is it working as expected (and proposed as better) test case.

**Pull request merged**
