### PR TITLE
AutomationId based on name fix

### PR DESCRIPTION
**Pull request by petvetbr**
## Set AutomationId based on x:Name property

Now the AutomationId property is set according to the control x:Name property.

For NumericUpDown:

- Textbox: "PART_TextBox{x:Name value}"
- DownButton : "PART_NumericDown{x:Name value}"
- UpButton: "PART_NumericUp{x:Name value}"

For Flyout:

-NavButton: "nav{x:Name value}"

#2166

### CODE REVIEW

**Comment by punker76** [comment]
@thoemmi What do you think? /cc @xxMUROxx

**Comment by thoemmi** [comment]
I don't know anything about the automation API, but it looks fine for me :blush:

**Comment by xxMUROxx** [comment]
Can someone explain in short what **Automation** is useful for?

**Comment by petvetbr** [comment]
@xxMUROxx there are 2 areas where automation is used a lot:

Automated UI tests
Accessibility

In both it is important to manipulate the UI using alternatives to de usual keyboard/mouse/touch methods, so that is when automation comes into play.

**Comment by xxMUROxx** [comment]
@petvetbr Ah, ok. Then I think the same behavior is missing for other custom controls that are implemented in this library too. e.g. ToggleSwith, DropDownButton, SplitButton, etc...

**Comment by petvetbr** [comment]
@xxMUROxx

Ok, I´ll take a look at the other controls and see if I can make them more "automation friendly",

**Comment by xxMUROxx** [comment]
@petvetbr :+1: 

One thing to point out. For custom controls created by this library you could introduce a method in e.g. NumericUpDown that attached the properties to the PART_ controls in order to avoid that the attached property is called in XAML. This has the advantage that if someone rewrites the template for e.g. NumericUpDown the _automation_ is applied too.

private void ApplyUiAutomation()
{
    _repeatDown.SetValue(Controls:AutomationHelper.DefaultAutomationId, ElementNumericDown);
    //...
}
what do you think?

/cc @punker76

**Comment by xxMUROxx** [comment]
I have looked into it a bit and found that the UI Elements should get exposed by [AutomationPeer Class](https://msdn.microsoft.com/en-us/library/system.windows.automation.peers.automationpeer.aspx). So it is done with ButtonAutomationPeer, TextBoxAutomationPeer.

Therefore I think it should be done also with NumericUpDown. Create a class NumericUpDownAutomationPeer and implement the exposure there

[UI Automation of a WPF Custom Control](https://msdn.microsoft.com/library/cc165614(v=vs.100).aspx)

**Pull request merged**
