### PR TITLE
Added a way to enable IntelliSense in XAML for the ResourceKeys

### PR DESCRIPTION
**Pull request by timunie**
**Describe the changes you have made to improve this project**
- Added a static Class that holds all the ResourceKeys as static strings => These can be found via IntelliSense 
- Created an Excel-File that helps keeping the `ResourceKeys` up to date.

Usage Example:
```
<Button Style="{StaticResource {x:Static MahApps:ResourceKeys.MahApps_Styles_Button_AccentedSquare}}"
        Foreground="{DynamicResource {x:Static MahApps:ResourceKeys.MahApps_Brushes_IdealForeground}}"
        Content="This is a Test" />
```

**Unit test**
Thinking about all the available Keys, it might be a good idea. Any guide / help available? How would one do this?

**Additional context**
With normal Keys: 
ResourcesCurrentImplementation

With the solution: 
ResourcesNewImplementation

**Closed Issues**
None as far as I can see.

### CODE REVIEW

**Comment by timunie** [comment]
UPDATE: The mentioned Excel-File is Attached here. It is not a good idea to ship it with the source I think :smile:.
[ResourceKeyHelper.xlsx](https://github.com/MahApps/MahApps.Metro/files/3712856/ResourceKeyHelper.xlsx)

Happy coding
Tim

**Comment by timunie** [comment]
Hi together,

after a short discussion with @punker76 we don't know if this PR is the best solution for IntelliSense in XAML. Therefor it will be on hold for the moment. If anyone wants a temporary solution i uploaded the needed file here. You just need to include it in your project, adjust the `NameSpace` and you are ready to go. 
[ResourceKeys.zip](https://github.com/MahApps/MahApps.Metro/files/3717437/ResourceKeys.zip)

Happy coding
Tim

**Comment by punker76** [comment]
@timunie I will close this, because the new VS 2019 16.4 supports this now. ❤️ 

>**Displaying resources for referenced assemblies:** XAML IntelliSense has been updated to support displaying XAML resources from a referenced assembly (when source is not available) for WPF Framework and WPF .NET Core projects.

**Comment by timunie** [comment]
@punker76 I thought the same. Thank you anyway. 

Happy updating
Tim

**Pull request closed without merging**
