### PR TITLE
[RFC] Adds a ToolBar helper

### PR DESCRIPTION
**Pull request by Evangelink**
## What changed?

Provides a ToolBar helper. This helper provides a way to tell if the current item is currently being displayed within the overflow panel or within the regular panel. It can be used to create special styles based on the item position.

See issue #2652.

### CODE REVIEW

**Comment by Evangelink** [comment]
@punker76 Don't know if it is a bug or just a different mechanism but using MahApps TreeHelper I don't end up with the parent object I am looking for whereas using the given TreeHelper it does work.

**Comment by avechuche** [comment]
Hello! Is this implemented? I can not use it. Thx!

**Comment by Evangelink** [comment]
Hi @punker76 !

I have tried to report my old PR on the up-to-date develop branch. Everything is building ok locally but it seems like something is wrong (references?) on the TeamCity build agent. Not sure whether I missed something (I have updated the shproj by hand cause it doesn't display the xaml pages).

Any help on what I have missed would be appreciated.

**Comment by punker76** [comment]
I get the same result, if I use the `ToolBar.IsOverflowItem` property, so I’m closing for now this PR.

Please let me know if you still need this extra property.

Thank you! 🙏

**Comment by Evangelink** [comment]
Hi @punker76,

I also have the same behavior using `ToolBar.IsOverflowItem`... Either I missed the property or either there was something else broken when I have developed this helper.

Anyway thank you for the time spent on this PR!

Keep up with the good work you are doing!

**Pull request closed without merging**
