### PR TITLE
Use the Glow to enable drop shadow (EnableDWMDropShadow)

### PR DESCRIPTION
**Pull request by punker76**
after this pr it's possible to have

- border
  + `BorderBrush="{DynamicResource AccentColorBrush}"`
- glow with border
  + `GlowBrush="{DynamicResource AccentColorBrush}"`
- glow without border
  + `BorderThickness="0"`
  + `GlowBrush="{DynamicResource AccentColorBrush}"`
- drop shadow
  + `BorderThickness="0"`
  + `GlowBrush="Black"`
- or drop shadow with
  + `EnableDWMDropShadow="True"`

Closes Window loses shadow [EnableDWMDropShadow] #1791

2015-02-13_15h05_08

### CODE REVIEW

**Comment by punker76** [comment]
@flagbug agreed with this?
/CC @thoemmi @AdditionalPylons

**Comment by thoemmi** [comment]
Looks ok to me. However, this is a breaking change for applications using `EnableDWMDropShadow`. Maybe you should add a change handler to `EnableDWMDropShadowProperty` which, when the property is set to `true`, sets `BorderThickness="0"` and `GlowBrush="Black"`.

**Comment by punker76** [comment]
@thoemmi thx, i also thought about the change handler after did the PR ;-)

**Comment by flagbug** [comment]
Works for me :+1:

**Comment by thoemmi** [comment]
I would have kept the `ObsoleteAttribute` on `MetroWindow.EnableDWMDropShadow`. It's still working under the hood so it's not broken, but users of MahApps.Metro should update their code to set `BorderThickness="0"` and `GlowBrush="Black"` directly.

**Comment by punker76** [comment]
@thoemmi agreed 9ded780d81900667662e32c3018a044c75393594

**Pull request merged**
