### PR TITLE
Use Microsoft.Xaml.Behaviors.Wpf instead the System.Windows.Interactivity

### LINKED ISSUE #3400: Use Microsoft.Xaml.Behaviors.Wpf instead the System.Windows.Interactivity
Use Microsoft.Xaml.Behaviors.Wpf as dependency from NuGet instead the System.Windows.Interactivity.dll

This will remove the reference to System.Windows.Interactivity.dll which is sometimes bad for other projects which are also use this dll.

With this change it's necessary to change the namespace too, so this is a breaking change for all others too.

https://blogs.msdn.microsoft.com/dotnet/2018/12/10/open-sourcing-xaml-behaviors-for-wpf/

### PR DESCRIPTION
**Pull request by punker76**
**Describe the changes you have made to improve this project**

Use Microsoft.Xaml.Behaviors.Wpf as dependency from NuGet instead the System.Windows.Interactivity.dll

This will remove the reference to System.Windows.Interactivity.dll which is sometimes bad for other projects which are also use this dll.

With this change it's necessary to change the namespace too, so this is a breaking change for all others too.

https://blogs.msdn.microsoft.com/dotnet/2018/12/10/open-sourcing-xaml-behaviors-for-wpf/

**Unit test**

-/-

**Additional context**

Steps to migrate:
1) Remove reference to `Microsoft.Expression.Interactions` and `System.Windows.Interactivity`
2) Install the `Microsoft.Xaml.Behaviors.Wpf` [NuGet package](https://www.nuget.org/packages/Microsoft.Xaml.Behaviors.Wpf).
3) XAML files – replace the xmlns namespaces `http://schemas.microsoft.com/expression/2010/interactivity` and `http://schemas.microsoft.com/expression/2010/interactions` with `http://schemas.microsoft.com/xaml/behaviors`
4) C# files – replace the usings in c# files `Microsoft.Xaml.Interactivity` and `Microsoft.Xaml.Interactions` with `Microsoft.Xaml.Behaviors`

**Closed Issues**

Closes #3400

### CODE REVIEW

**Comment by rabiadhikari** [comment]
Could you please elaborate how to use the behaviors dll as embedded resources? The Windows  Interactivity dll worked quite nicely and I am having difficulty using the same for behaviors. Any pointers  to some examples would be fantastic.

**Comment by punker76** [comment]
@rabiadhikari I think it should be the same. Or you can try using [Costura Fody](https://github.com/Fody/Costura) and use their embedded fantastic job.

**Comment by rabiadhikari** [comment]
Thank you @punker76 for your suggestion. Loading dll into the app isn't the issue. My codes worked when using Windows Interactivity dll while when I changed the references to Behaviors.Wpf, the same code doesn't work as expected. Perhaps I am missing something and thus wondering to see an example if someone could point me to one. Googling hasn't helped so far thus the request. I am using Relay command and other setup for MVVM with WPF. Output file is a DLL document to be used as Addin.

**Comment by punker76** [comment]
@rabiadhikari The namespace is different to the old one, so you should check this.

For XAML

```
xmlns:i="http://schemas.microsoft.com/xaml/behaviors"
```

and for code behind

```
using Microsoft.Xaml.Behaviors;
```

**Pull request merged**
