### PR TITLE
Add TitleHorizontalAlignment property on the MetroWindow.

### PR DESCRIPTION
**Pull request by spasas**
Our designer requested the title to be shown on the left of the Window. It may be useful for other projects as well.

### CODE REVIEW

**Comment by thoemmi** [comment]
This is similar to #2007. Change the `TitleTemplate` of your window.

**Comment by spasas** [comment]
I agree that it is pretty close to #2007 almost the same even. It's your call, but it seems overkill to me to template the title if I only want it to be aligned left.

**Comment by thoemmi** [comment]
**You** only want it to be left aligned. The next user might want to have bold text, another one italic. IMHO there are already way too many dependency properties on `MetroWindow`, and as shown in #2007 the title is really simple to style.

**Comment by spasas** [comment]
Fair enough :) You can cancel the pull request then.

**Comment by thoemmi** [comment]
@spasas don't get me wrong, your requirement is totally comprehensible. It's just that it would open a can of worms :wink:

**Pull request closed without merging**
